// Code generated by ent, DO NOT EDIT.

package grsaitaskpayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the grsaitaskpayload type in the database.
	Label = "grsai_task_payload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "settlement_id"
	// FieldCiphertext holds the string denoting the ciphertext field in the database.
	FieldCiphertext = "ciphertext"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSettlement holds the string denoting the settlement edge name in mutations.
	EdgeSettlement = "settlement"
	// GrsaiSettlementFieldID holds the string denoting the ID field of the GrsaiSettlement.
	GrsaiSettlementFieldID = "id"
	// Table holds the table name of the grsaitaskpayload in the database.
	Table = "grsai_task_payloads"
	// SettlementTable is the table that holds the settlement relation/edge.
	SettlementTable = "grsai_task_payloads"
	// SettlementInverseTable is the table name for the GrsaiSettlement entity.
	// It exists in this package in order to avoid circular dependency with the "grsaisettlement" package.
	SettlementInverseTable = "grsai_settlements"
	// SettlementColumn is the table column denoting the settlement relation/edge.
	SettlementColumn = "settlement_id"
)

// Columns holds all SQL columns for grsaitaskpayload fields.
var Columns = []string{
	FieldID,
	FieldCiphertext,
	FieldExpiresAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "grsai_task_payloads"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"settlement_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GrsaiTaskPayload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCiphertext orders the results by the ciphertext field.
func ByCiphertext(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCiphertext, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySettlementField orders the results by settlement field.
func BySettlementField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSettlementStep(), sql.OrderByField(field, opts...))
	}
}
func newSettlementStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SettlementInverseTable, GrsaiSettlementFieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, SettlementTable, SettlementColumn),
	)
}
