// Code generated by ent, DO NOT EDIT.

package grsaitaskpayload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLTE(FieldID, id))
}

// Ciphertext applies equality check predicate on the "ciphertext" field. It's identical to CiphertextEQ.
func Ciphertext(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldCiphertext, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldUpdatedAt, v))
}

// CiphertextEQ applies the EQ predicate on the "ciphertext" field.
func CiphertextEQ(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldCiphertext, v))
}

// CiphertextNEQ applies the NEQ predicate on the "ciphertext" field.
func CiphertextNEQ(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNEQ(FieldCiphertext, v))
}

// CiphertextIn applies the In predicate on the "ciphertext" field.
func CiphertextIn(vs ...string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldIn(FieldCiphertext, vs...))
}

// CiphertextNotIn applies the NotIn predicate on the "ciphertext" field.
func CiphertextNotIn(vs ...string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNotIn(FieldCiphertext, vs...))
}

// CiphertextGT applies the GT predicate on the "ciphertext" field.
func CiphertextGT(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGT(FieldCiphertext, v))
}

// CiphertextGTE applies the GTE predicate on the "ciphertext" field.
func CiphertextGTE(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGTE(FieldCiphertext, v))
}

// CiphertextLT applies the LT predicate on the "ciphertext" field.
func CiphertextLT(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLT(FieldCiphertext, v))
}

// CiphertextLTE applies the LTE predicate on the "ciphertext" field.
func CiphertextLTE(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLTE(FieldCiphertext, v))
}

// CiphertextContains applies the Contains predicate on the "ciphertext" field.
func CiphertextContains(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldContains(FieldCiphertext, v))
}

// CiphertextHasPrefix applies the HasPrefix predicate on the "ciphertext" field.
func CiphertextHasPrefix(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldHasPrefix(FieldCiphertext, v))
}

// CiphertextHasSuffix applies the HasSuffix predicate on the "ciphertext" field.
func CiphertextHasSuffix(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldHasSuffix(FieldCiphertext, v))
}

// CiphertextEqualFold applies the EqualFold predicate on the "ciphertext" field.
func CiphertextEqualFold(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEqualFold(FieldCiphertext, v))
}

// CiphertextContainsFold applies the ContainsFold predicate on the "ciphertext" field.
func CiphertextContainsFold(v string) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldContainsFold(FieldCiphertext, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GrsaiTaskPayload) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GrsaiTaskPayload) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GrsaiTaskPayload) predicate.GrsaiTaskPayload {
	return predicate.GrsaiTaskPayload(sql.NotPredicates(p))
}
