// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grsaisettlement"
	"github.com/Wei-Shaw/sub2api/ent/grsaitaskpayload"
)

// GrsaiTaskPayloadCreate is the builder for creating a GrsaiTaskPayload entity.
type GrsaiTaskPayloadCreate struct {
	config
	mutation *GrsaiTaskPayloadMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCiphertext sets the "ciphertext" field.
func (_c *GrsaiTaskPayloadCreate) SetCiphertext(v string) *GrsaiTaskPayloadCreate {
	_c.mutation.SetCiphertext(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *GrsaiTaskPayloadCreate) SetExpiresAt(v time.Time) *GrsaiTaskPayloadCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *GrsaiTaskPayloadCreate) SetCreatedAt(v time.Time) *GrsaiTaskPayloadCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *GrsaiTaskPayloadCreate) SetNillableCreatedAt(v *time.Time) *GrsaiTaskPayloadCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *GrsaiTaskPayloadCreate) SetUpdatedAt(v time.Time) *GrsaiTaskPayloadCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *GrsaiTaskPayloadCreate) SetNillableUpdatedAt(v *time.Time) *GrsaiTaskPayloadCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *GrsaiTaskPayloadCreate) SetID(v int64) *GrsaiTaskPayloadCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetSettlementID sets the "settlement" edge to the GrsaiSettlement entity by ID.
func (_c *GrsaiTaskPayloadCreate) SetSettlementID(id int64) *GrsaiTaskPayloadCreate {
	_c.mutation.SetSettlementID(id)
	return _c
}

// SetSettlement sets the "settlement" edge to the GrsaiSettlement entity.
func (_c *GrsaiTaskPayloadCreate) SetSettlement(v *GrsaiSettlement) *GrsaiTaskPayloadCreate {
	return _c.SetSettlementID(v.ID)
}

// Mutation returns the GrsaiTaskPayloadMutation object of the builder.
func (_c *GrsaiTaskPayloadCreate) Mutation() *GrsaiTaskPayloadMutation {
	return _c.mutation
}

// Save creates the GrsaiTaskPayload in the database.
func (_c *GrsaiTaskPayloadCreate) Save(ctx context.Context) (*GrsaiTaskPayload, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GrsaiTaskPayloadCreate) SaveX(ctx context.Context) *GrsaiTaskPayload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GrsaiTaskPayloadCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GrsaiTaskPayloadCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GrsaiTaskPayloadCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := grsaitaskpayload.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := grsaitaskpayload.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GrsaiTaskPayloadCreate) check() error {
	if _, ok := _c.mutation.Ciphertext(); !ok {
		return &ValidationError{Name: "ciphertext", err: errors.New(`ent: missing required field "GrsaiTaskPayload.ciphertext"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "GrsaiTaskPayload.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "GrsaiTaskPayload.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "GrsaiTaskPayload.updated_at"`)}
	}
	if len(_c.mutation.SettlementIDs()) == 0 {
		return &ValidationError{Name: "settlement", err: errors.New(`ent: missing required edge "GrsaiTaskPayload.settlement"`)}
	}
	return nil
}

func (_c *GrsaiTaskPayloadCreate) sqlSave(ctx context.Context) (*GrsaiTaskPayload, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GrsaiTaskPayloadCreate) createSpec() (*GrsaiTaskPayload, *sqlgraph.CreateSpec) {
	var (
		_node = &GrsaiTaskPayload{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(grsaitaskpayload.Table, sqlgraph.NewFieldSpec(grsaitaskpayload.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Ciphertext(); ok {
		_spec.SetField(grsaitaskpayload.FieldCiphertext, field.TypeString, value)
		_node.Ciphertext = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(grsaitaskpayload.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(grsaitaskpayload.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(grsaitaskpayload.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.SettlementIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   grsaitaskpayload.SettlementTable,
			Columns: []string{grsaitaskpayload.SettlementColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(grsaisettlement.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.settlement_id = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GrsaiTaskPayload.Create().
//		SetCiphertext(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GrsaiTaskPayloadUpsert) {
//			SetCiphertext(v+v).
//		}).
//		Exec(ctx)
func (_c *GrsaiTaskPayloadCreate) OnConflict(opts ...sql.ConflictOption) *GrsaiTaskPayloadUpsertOne {
	_c.conflict = opts
	return &GrsaiTaskPayloadUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GrsaiTaskPayload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GrsaiTaskPayloadCreate) OnConflictColumns(columns ...string) *GrsaiTaskPayloadUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GrsaiTaskPayloadUpsertOne{
		create: _c,
	}
}

type (
	// GrsaiTaskPayloadUpsertOne is the builder for "upsert"-ing
	//  one GrsaiTaskPayload node.
	GrsaiTaskPayloadUpsertOne struct {
		create *GrsaiTaskPayloadCreate
	}

	// GrsaiTaskPayloadUpsert is the "OnConflict" setter.
	GrsaiTaskPayloadUpsert struct {
		*sql.UpdateSet
	}
)

// SetCiphertext sets the "ciphertext" field.
func (u *GrsaiTaskPayloadUpsert) SetCiphertext(v string) *GrsaiTaskPayloadUpsert {
	u.Set(grsaitaskpayload.FieldCiphertext, v)
	return u
}

// UpdateCiphertext sets the "ciphertext" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsert) UpdateCiphertext() *GrsaiTaskPayloadUpsert {
	u.SetExcluded(grsaitaskpayload.FieldCiphertext)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *GrsaiTaskPayloadUpsert) SetExpiresAt(v time.Time) *GrsaiTaskPayloadUpsert {
	u.Set(grsaitaskpayload.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsert) UpdateExpiresAt() *GrsaiTaskPayloadUpsert {
	u.SetExcluded(grsaitaskpayload.FieldExpiresAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GrsaiTaskPayloadUpsert) SetUpdatedAt(v time.Time) *GrsaiTaskPayloadUpsert {
	u.Set(grsaitaskpayload.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsert) UpdateUpdatedAt() *GrsaiTaskPayloadUpsert {
	u.SetExcluded(grsaitaskpayload.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.GrsaiTaskPayload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(grsaitaskpayload.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GrsaiTaskPayloadUpsertOne) UpdateNewValues() *GrsaiTaskPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(grsaitaskpayload.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(grsaitaskpayload.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GrsaiTaskPayload.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *GrsaiTaskPayloadUpsertOne) Ignore() *GrsaiTaskPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GrsaiTaskPayloadUpsertOne) DoNothing() *GrsaiTaskPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GrsaiTaskPayloadCreate.OnConflict
// documentation for more info.
func (u *GrsaiTaskPayloadUpsertOne) Update(set func(*GrsaiTaskPayloadUpsert)) *GrsaiTaskPayloadUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GrsaiTaskPayloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetCiphertext sets the "ciphertext" field.
func (u *GrsaiTaskPayloadUpsertOne) SetCiphertext(v string) *GrsaiTaskPayloadUpsertOne {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.SetCiphertext(v)
	})
}

// UpdateCiphertext sets the "ciphertext" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsertOne) UpdateCiphertext() *GrsaiTaskPayloadUpsertOne {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.UpdateCiphertext()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *GrsaiTaskPayloadUpsertOne) SetExpiresAt(v time.Time) *GrsaiTaskPayloadUpsertOne {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsertOne) UpdateExpiresAt() *GrsaiTaskPayloadUpsertOne {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GrsaiTaskPayloadUpsertOne) SetUpdatedAt(v time.Time) *GrsaiTaskPayloadUpsertOne {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsertOne) UpdateUpdatedAt() *GrsaiTaskPayloadUpsertOne {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GrsaiTaskPayloadUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GrsaiTaskPayloadCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GrsaiTaskPayloadUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *GrsaiTaskPayloadUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *GrsaiTaskPayloadUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// GrsaiTaskPayloadCreateBulk is the builder for creating many GrsaiTaskPayload entities in bulk.
type GrsaiTaskPayloadCreateBulk struct {
	config
	err      error
	builders []*GrsaiTaskPayloadCreate
	conflict []sql.ConflictOption
}

// Save creates the GrsaiTaskPayload entities in the database.
func (_c *GrsaiTaskPayloadCreateBulk) Save(ctx context.Context) ([]*GrsaiTaskPayload, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GrsaiTaskPayload, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GrsaiTaskPayloadMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GrsaiTaskPayloadCreateBulk) SaveX(ctx context.Context) []*GrsaiTaskPayload {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GrsaiTaskPayloadCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GrsaiTaskPayloadCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.GrsaiTaskPayload.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.GrsaiTaskPayloadUpsert) {
//			SetCiphertext(v+v).
//		}).
//		Exec(ctx)
func (_c *GrsaiTaskPayloadCreateBulk) OnConflict(opts ...sql.ConflictOption) *GrsaiTaskPayloadUpsertBulk {
	_c.conflict = opts
	return &GrsaiTaskPayloadUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.GrsaiTaskPayload.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *GrsaiTaskPayloadCreateBulk) OnConflictColumns(columns ...string) *GrsaiTaskPayloadUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &GrsaiTaskPayloadUpsertBulk{
		create: _c,
	}
}

// GrsaiTaskPayloadUpsertBulk is the builder for "upsert"-ing
// a bulk of GrsaiTaskPayload nodes.
type GrsaiTaskPayloadUpsertBulk struct {
	create *GrsaiTaskPayloadCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.GrsaiTaskPayload.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(grsaitaskpayload.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *GrsaiTaskPayloadUpsertBulk) UpdateNewValues() *GrsaiTaskPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(grsaitaskpayload.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(grsaitaskpayload.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.GrsaiTaskPayload.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *GrsaiTaskPayloadUpsertBulk) Ignore() *GrsaiTaskPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *GrsaiTaskPayloadUpsertBulk) DoNothing() *GrsaiTaskPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the GrsaiTaskPayloadCreateBulk.OnConflict
// documentation for more info.
func (u *GrsaiTaskPayloadUpsertBulk) Update(set func(*GrsaiTaskPayloadUpsert)) *GrsaiTaskPayloadUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&GrsaiTaskPayloadUpsert{UpdateSet: update})
	}))
	return u
}

// SetCiphertext sets the "ciphertext" field.
func (u *GrsaiTaskPayloadUpsertBulk) SetCiphertext(v string) *GrsaiTaskPayloadUpsertBulk {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.SetCiphertext(v)
	})
}

// UpdateCiphertext sets the "ciphertext" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsertBulk) UpdateCiphertext() *GrsaiTaskPayloadUpsertBulk {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.UpdateCiphertext()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *GrsaiTaskPayloadUpsertBulk) SetExpiresAt(v time.Time) *GrsaiTaskPayloadUpsertBulk {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsertBulk) UpdateExpiresAt() *GrsaiTaskPayloadUpsertBulk {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *GrsaiTaskPayloadUpsertBulk) SetUpdatedAt(v time.Time) *GrsaiTaskPayloadUpsertBulk {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *GrsaiTaskPayloadUpsertBulk) UpdateUpdatedAt() *GrsaiTaskPayloadUpsertBulk {
	return u.Update(func(s *GrsaiTaskPayloadUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *GrsaiTaskPayloadUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the GrsaiTaskPayloadCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for GrsaiTaskPayloadCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *GrsaiTaskPayloadUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
