// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/grsaisettlement"
	"github.com/Wei-Shaw/sub2api/ent/grsaitaskpayload"
)

// GrsaiSettlement is the model entity for the GrsaiSettlement schema.
type GrsaiSettlement struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// BaseUnitPrice holds the value of the "base_unit_price" field.
	BaseUnitPrice float64 `json:"base_unit_price,omitempty"`
	// GroupRateMultiplier holds the value of the "group_rate_multiplier" field.
	GroupRateMultiplier float64 `json:"group_rate_multiplier,omitempty"`
	// AccountRateMultiplier holds the value of the "account_rate_multiplier" field.
	AccountRateMultiplier float64 `json:"account_rate_multiplier,omitempty"`
	// BillableUnitPrice holds the value of the "billable_unit_price" field.
	BillableUnitPrice float64 `json:"billable_unit_price,omitempty"`
	// RequestedImageCount holds the value of the "requested_image_count" field.
	RequestedImageCount int `json:"requested_image_count,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// BillingIdempotencyKey holds the value of the "billing_idempotency_key" field.
	BillingIdempotencyKey string `json:"billing_idempotency_key,omitempty"`
	// PublicTaskID holds the value of the "public_task_id" field.
	PublicTaskID *string `json:"public_task_id,omitempty"`
	// DeliveryMode holds the value of the "delivery_mode" field.
	DeliveryMode string `json:"delivery_mode,omitempty"`
	// AsyncStartedAt holds the value of the "async_started_at" field.
	AsyncStartedAt *time.Time `json:"async_started_at,omitempty"`
	// Progress holds the value of the "progress" field.
	Progress int `json:"progress,omitempty"`
	// ResultUrls holds the value of the "result_urls" field.
	ResultUrls []string `json:"result_urls,omitempty"`
	// HoldAmount holds the value of the "hold_amount" field.
	HoldAmount float64 `json:"hold_amount,omitempty"`
	// HoldState holds the value of the "hold_state" field.
	HoldState string `json:"hold_state,omitempty"`
	// PayloadDeleteAfter holds the value of the "payload_delete_after" field.
	PayloadDeleteAfter *time.Time `json:"payload_delete_after,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// UpstreamTaskID holds the value of the "upstream_task_id" field.
	UpstreamTaskID *string `json:"upstream_task_id,omitempty"`
	// UpstreamStatus holds the value of the "upstream_status" field.
	UpstreamStatus string `json:"upstream_status,omitempty"`
	// InternalStatus holds the value of the "internal_status" field.
	InternalStatus string `json:"internal_status,omitempty"`
	// RetryCount holds the value of the "retry_count" field.
	RetryCount int `json:"retry_count,omitempty"`
	// SettlementRetryCount holds the value of the "settlement_retry_count" field.
	SettlementRetryCount int `json:"settlement_retry_count,omitempty"`
	// ClaimVersion holds the value of the "claim_version" field.
	ClaimVersion int64 `json:"claim_version,omitempty"`
	// NextAttemptAt holds the value of the "next_attempt_at" field.
	NextAttemptAt time.Time `json:"next_attempt_at,omitempty"`
	// LastErrorSummary holds the value of the "last_error_summary" field.
	LastErrorSummary *string `json:"last_error_summary,omitempty"`
	// SettledAmount holds the value of the "settled_amount" field.
	SettledAmount *float64 `json:"settled_amount,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UpstreamBoundAt holds the value of the "upstream_bound_at" field.
	UpstreamBoundAt *time.Time `json:"upstream_bound_at,omitempty"`
	// ResultUpdatedAt holds the value of the "result_updated_at" field.
	ResultUpdatedAt *time.Time `json:"result_updated_at,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GrsaiSettlementQuery when eager-loading is set.
	Edges        GrsaiSettlementEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GrsaiSettlementEdges holds the relations/edges for other nodes in the graph.
type GrsaiSettlementEdges struct {
	// TaskPayload holds the value of the task_payload edge.
	TaskPayload *GrsaiTaskPayload `json:"task_payload,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TaskPayloadOrErr returns the TaskPayload value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GrsaiSettlementEdges) TaskPayloadOrErr() (*GrsaiTaskPayload, error) {
	if e.TaskPayload != nil {
		return e.TaskPayload, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: grsaitaskpayload.Label}
	}
	return nil, &NotLoadedError{edge: "task_payload"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GrsaiSettlement) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grsaisettlement.FieldResultUrls:
			values[i] = new([]byte)
		case grsaisettlement.FieldBaseUnitPrice, grsaisettlement.FieldGroupRateMultiplier, grsaisettlement.FieldAccountRateMultiplier, grsaisettlement.FieldBillableUnitPrice, grsaisettlement.FieldHoldAmount, grsaisettlement.FieldSettledAmount:
			values[i] = new(sql.NullFloat64)
		case grsaisettlement.FieldID, grsaisettlement.FieldAccountID, grsaisettlement.FieldGroupID, grsaisettlement.FieldUserID, grsaisettlement.FieldAPIKeyID, grsaisettlement.FieldRequestedImageCount, grsaisettlement.FieldProgress, grsaisettlement.FieldRetryCount, grsaisettlement.FieldSettlementRetryCount, grsaisettlement.FieldClaimVersion:
			values[i] = new(sql.NullInt64)
		case grsaisettlement.FieldModel, grsaisettlement.FieldCurrency, grsaisettlement.FieldBillingIdempotencyKey, grsaisettlement.FieldPublicTaskID, grsaisettlement.FieldDeliveryMode, grsaisettlement.FieldHoldState, grsaisettlement.FieldUpstreamTaskID, grsaisettlement.FieldUpstreamStatus, grsaisettlement.FieldInternalStatus, grsaisettlement.FieldLastErrorSummary:
			values[i] = new(sql.NullString)
		case grsaisettlement.FieldAsyncStartedAt, grsaisettlement.FieldPayloadDeleteAfter, grsaisettlement.FieldExpiresAt, grsaisettlement.FieldNextAttemptAt, grsaisettlement.FieldCreatedAt, grsaisettlement.FieldUpdatedAt, grsaisettlement.FieldUpstreamBoundAt, grsaisettlement.FieldResultUpdatedAt, grsaisettlement.FieldSettledAt, grsaisettlement.FieldClosedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GrsaiSettlement fields.
func (_m *GrsaiSettlement) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grsaisettlement.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case grsaisettlement.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case grsaisettlement.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case grsaisettlement.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case grsaisettlement.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case grsaisettlement.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case grsaisettlement.FieldBaseUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field base_unit_price", values[i])
			} else if value.Valid {
				_m.BaseUnitPrice = value.Float64
			}
		case grsaisettlement.FieldGroupRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field group_rate_multiplier", values[i])
			} else if value.Valid {
				_m.GroupRateMultiplier = value.Float64
			}
		case grsaisettlement.FieldAccountRateMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field account_rate_multiplier", values[i])
			} else if value.Valid {
				_m.AccountRateMultiplier = value.Float64
			}
		case grsaisettlement.FieldBillableUnitPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field billable_unit_price", values[i])
			} else if value.Valid {
				_m.BillableUnitPrice = value.Float64
			}
		case grsaisettlement.FieldRequestedImageCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field requested_image_count", values[i])
			} else if value.Valid {
				_m.RequestedImageCount = int(value.Int64)
			}
		case grsaisettlement.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case grsaisettlement.FieldBillingIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_idempotency_key", values[i])
			} else if value.Valid {
				_m.BillingIdempotencyKey = value.String
			}
		case grsaisettlement.FieldPublicTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_task_id", values[i])
			} else if value.Valid {
				_m.PublicTaskID = new(string)
				*_m.PublicTaskID = value.String
			}
		case grsaisettlement.FieldDeliveryMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_mode", values[i])
			} else if value.Valid {
				_m.DeliveryMode = value.String
			}
		case grsaisettlement.FieldAsyncStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field async_started_at", values[i])
			} else if value.Valid {
				_m.AsyncStartedAt = new(time.Time)
				*_m.AsyncStartedAt = value.Time
			}
		case grsaisettlement.FieldProgress:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field progress", values[i])
			} else if value.Valid {
				_m.Progress = int(value.Int64)
			}
		case grsaisettlement.FieldResultUrls:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result_urls", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ResultUrls); err != nil {
					return fmt.Errorf("unmarshal field result_urls: %w", err)
				}
			}
		case grsaisettlement.FieldHoldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hold_amount", values[i])
			} else if value.Valid {
				_m.HoldAmount = value.Float64
			}
		case grsaisettlement.FieldHoldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field hold_state", values[i])
			} else if value.Valid {
				_m.HoldState = value.String
			}
		case grsaisettlement.FieldPayloadDeleteAfter:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field payload_delete_after", values[i])
			} else if value.Valid {
				_m.PayloadDeleteAfter = new(time.Time)
				*_m.PayloadDeleteAfter = value.Time
			}
		case grsaisettlement.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case grsaisettlement.FieldUpstreamTaskID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_task_id", values[i])
			} else if value.Valid {
				_m.UpstreamTaskID = new(string)
				*_m.UpstreamTaskID = value.String
			}
		case grsaisettlement.FieldUpstreamStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_status", values[i])
			} else if value.Valid {
				_m.UpstreamStatus = value.String
			}
		case grsaisettlement.FieldInternalStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field internal_status", values[i])
			} else if value.Valid {
				_m.InternalStatus = value.String
			}
		case grsaisettlement.FieldRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_count", values[i])
			} else if value.Valid {
				_m.RetryCount = int(value.Int64)
			}
		case grsaisettlement.FieldSettlementRetryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_retry_count", values[i])
			} else if value.Valid {
				_m.SettlementRetryCount = int(value.Int64)
			}
		case grsaisettlement.FieldClaimVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field claim_version", values[i])
			} else if value.Valid {
				_m.ClaimVersion = value.Int64
			}
		case grsaisettlement.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = value.Time
			}
		case grsaisettlement.FieldLastErrorSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error_summary", values[i])
			} else if value.Valid {
				_m.LastErrorSummary = new(string)
				*_m.LastErrorSummary = value.String
			}
		case grsaisettlement.FieldSettledAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field settled_amount", values[i])
			} else if value.Valid {
				_m.SettledAmount = new(float64)
				*_m.SettledAmount = value.Float64
			}
		case grsaisettlement.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case grsaisettlement.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case grsaisettlement.FieldUpstreamBoundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_bound_at", values[i])
			} else if value.Valid {
				_m.UpstreamBoundAt = new(time.Time)
				*_m.UpstreamBoundAt = value.Time
			}
		case grsaisettlement.FieldResultUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field result_updated_at", values[i])
			} else if value.Valid {
				_m.ResultUpdatedAt = new(time.Time)
				*_m.ResultUpdatedAt = value.Time
			}
		case grsaisettlement.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		case grsaisettlement.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GrsaiSettlement.
// This includes values selected through modifiers, order, etc.
func (_m *GrsaiSettlement) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTaskPayload queries the "task_payload" edge of the GrsaiSettlement entity.
func (_m *GrsaiSettlement) QueryTaskPayload() *GrsaiTaskPayloadQuery {
	return NewGrsaiSettlementClient(_m.config).QueryTaskPayload(_m)
}

// Update returns a builder for updating this GrsaiSettlement.
// Note that you need to call GrsaiSettlement.Unwrap() before calling this method if this GrsaiSettlement
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GrsaiSettlement) Update() *GrsaiSettlementUpdateOne {
	return NewGrsaiSettlementClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GrsaiSettlement entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GrsaiSettlement) Unwrap() *GrsaiSettlement {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GrsaiSettlement is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GrsaiSettlement) String() string {
	var builder strings.Builder
	builder.WriteString("GrsaiSettlement(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("base_unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.BaseUnitPrice))
	builder.WriteString(", ")
	builder.WriteString("group_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("account_rate_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountRateMultiplier))
	builder.WriteString(", ")
	builder.WriteString("billable_unit_price=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillableUnitPrice))
	builder.WriteString(", ")
	builder.WriteString("requested_image_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestedImageCount))
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("billing_idempotency_key=")
	builder.WriteString(_m.BillingIdempotencyKey)
	builder.WriteString(", ")
	if v := _m.PublicTaskID; v != nil {
		builder.WriteString("public_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("delivery_mode=")
	builder.WriteString(_m.DeliveryMode)
	builder.WriteString(", ")
	if v := _m.AsyncStartedAt; v != nil {
		builder.WriteString("async_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("progress=")
	builder.WriteString(fmt.Sprintf("%v", _m.Progress))
	builder.WriteString(", ")
	builder.WriteString("result_urls=")
	builder.WriteString(fmt.Sprintf("%v", _m.ResultUrls))
	builder.WriteString(", ")
	builder.WriteString("hold_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.HoldAmount))
	builder.WriteString(", ")
	builder.WriteString("hold_state=")
	builder.WriteString(_m.HoldState)
	builder.WriteString(", ")
	if v := _m.PayloadDeleteAfter; v != nil {
		builder.WriteString("payload_delete_after=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpstreamTaskID; v != nil {
		builder.WriteString("upstream_task_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("upstream_status=")
	builder.WriteString(_m.UpstreamStatus)
	builder.WriteString(", ")
	builder.WriteString("internal_status=")
	builder.WriteString(_m.InternalStatus)
	builder.WriteString(", ")
	builder.WriteString("retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryCount))
	builder.WriteString(", ")
	builder.WriteString("settlement_retry_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettlementRetryCount))
	builder.WriteString(", ")
	builder.WriteString("claim_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClaimVersion))
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(_m.NextAttemptAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LastErrorSummary; v != nil {
		builder.WriteString("last_error_summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SettledAmount; v != nil {
		builder.WriteString("settled_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.UpstreamBoundAt; v != nil {
		builder.WriteString("upstream_bound_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResultUpdatedAt; v != nil {
		builder.WriteString("result_updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GrsaiSettlements is a parsable slice of GrsaiSettlement.
type GrsaiSettlements []*GrsaiSettlement
