// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grsaisettlement"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GrsaiSettlementDelete is the builder for deleting a GrsaiSettlement entity.
type GrsaiSettlementDelete struct {
	config
	hooks    []Hook
	mutation *GrsaiSettlementMutation
}

// Where appends a list predicates to the GrsaiSettlementDelete builder.
func (_d *GrsaiSettlementDelete) Where(ps ...predicate.GrsaiSettlement) *GrsaiSettlementDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GrsaiSettlementDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GrsaiSettlementDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GrsaiSettlementDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grsaisettlement.Table, sqlgraph.NewFieldSpec(grsaisettlement.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GrsaiSettlementDeleteOne is the builder for deleting a single GrsaiSettlement entity.
type GrsaiSettlementDeleteOne struct {
	_d *GrsaiSettlementDelete
}

// Where appends a list predicates to the GrsaiSettlementDelete builder.
func (_d *GrsaiSettlementDeleteOne) Where(ps ...predicate.GrsaiSettlement) *GrsaiSettlementDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GrsaiSettlementDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grsaisettlement.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GrsaiSettlementDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
