// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grsaitaskpayload"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GrsaiTaskPayloadUpdate is the builder for updating GrsaiTaskPayload entities.
type GrsaiTaskPayloadUpdate struct {
	config
	hooks    []Hook
	mutation *GrsaiTaskPayloadMutation
}

// Where appends a list predicates to the GrsaiTaskPayloadUpdate builder.
func (_u *GrsaiTaskPayloadUpdate) Where(ps ...predicate.GrsaiTaskPayload) *GrsaiTaskPayloadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCiphertext sets the "ciphertext" field.
func (_u *GrsaiTaskPayloadUpdate) SetCiphertext(v string) *GrsaiTaskPayloadUpdate {
	_u.mutation.SetCiphertext(v)
	return _u
}

// SetNillableCiphertext sets the "ciphertext" field if the given value is not nil.
func (_u *GrsaiTaskPayloadUpdate) SetNillableCiphertext(v *string) *GrsaiTaskPayloadUpdate {
	if v != nil {
		_u.SetCiphertext(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *GrsaiTaskPayloadUpdate) SetExpiresAt(v time.Time) *GrsaiTaskPayloadUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *GrsaiTaskPayloadUpdate) SetNillableExpiresAt(v *time.Time) *GrsaiTaskPayloadUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GrsaiTaskPayloadUpdate) SetUpdatedAt(v time.Time) *GrsaiTaskPayloadUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GrsaiTaskPayloadMutation object of the builder.
func (_u *GrsaiTaskPayloadUpdate) Mutation() *GrsaiTaskPayloadMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GrsaiTaskPayloadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrsaiTaskPayloadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GrsaiTaskPayloadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrsaiTaskPayloadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GrsaiTaskPayloadUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grsaitaskpayload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GrsaiTaskPayloadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(grsaitaskpayload.Table, grsaitaskpayload.Columns, sqlgraph.NewFieldSpec(grsaitaskpayload.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ciphertext(); ok {
		_spec.SetField(grsaitaskpayload.FieldCiphertext, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(grsaitaskpayload.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grsaitaskpayload.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grsaitaskpayload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GrsaiTaskPayloadUpdateOne is the builder for updating a single GrsaiTaskPayload entity.
type GrsaiTaskPayloadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GrsaiTaskPayloadMutation
}

// SetCiphertext sets the "ciphertext" field.
func (_u *GrsaiTaskPayloadUpdateOne) SetCiphertext(v string) *GrsaiTaskPayloadUpdateOne {
	_u.mutation.SetCiphertext(v)
	return _u
}

// SetNillableCiphertext sets the "ciphertext" field if the given value is not nil.
func (_u *GrsaiTaskPayloadUpdateOne) SetNillableCiphertext(v *string) *GrsaiTaskPayloadUpdateOne {
	if v != nil {
		_u.SetCiphertext(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *GrsaiTaskPayloadUpdateOne) SetExpiresAt(v time.Time) *GrsaiTaskPayloadUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *GrsaiTaskPayloadUpdateOne) SetNillableExpiresAt(v *time.Time) *GrsaiTaskPayloadUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GrsaiTaskPayloadUpdateOne) SetUpdatedAt(v time.Time) *GrsaiTaskPayloadUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the GrsaiTaskPayloadMutation object of the builder.
func (_u *GrsaiTaskPayloadUpdateOne) Mutation() *GrsaiTaskPayloadMutation {
	return _u.mutation
}

// Where appends a list predicates to the GrsaiTaskPayloadUpdate builder.
func (_u *GrsaiTaskPayloadUpdateOne) Where(ps ...predicate.GrsaiTaskPayload) *GrsaiTaskPayloadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GrsaiTaskPayloadUpdateOne) Select(field string, fields ...string) *GrsaiTaskPayloadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GrsaiTaskPayload entity.
func (_u *GrsaiTaskPayloadUpdateOne) Save(ctx context.Context) (*GrsaiTaskPayload, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrsaiTaskPayloadUpdateOne) SaveX(ctx context.Context) *GrsaiTaskPayload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GrsaiTaskPayloadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrsaiTaskPayloadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GrsaiTaskPayloadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grsaitaskpayload.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *GrsaiTaskPayloadUpdateOne) sqlSave(ctx context.Context) (_node *GrsaiTaskPayload, err error) {
	_spec := sqlgraph.NewUpdateSpec(grsaitaskpayload.Table, grsaitaskpayload.Columns, sqlgraph.NewFieldSpec(grsaitaskpayload.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GrsaiTaskPayload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grsaitaskpayload.FieldID)
		for _, f := range fields {
			if !grsaitaskpayload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grsaitaskpayload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Ciphertext(); ok {
		_spec.SetField(grsaitaskpayload.FieldCiphertext, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(grsaitaskpayload.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grsaitaskpayload.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &GrsaiTaskPayload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grsaitaskpayload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
