// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json/jsontext"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grsaisettlement"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GrsaiSettlementUpdate is the builder for updating GrsaiSettlement entities.
type GrsaiSettlementUpdate struct {
	config
	hooks    []Hook
	mutation *GrsaiSettlementMutation
}

// Where appends a list predicates to the GrsaiSettlementUpdate builder.
func (_u *GrsaiSettlementUpdate) Where(ps ...predicate.GrsaiSettlement) *GrsaiSettlementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *GrsaiSettlementUpdate) SetAccountID(v int64) *GrsaiSettlementUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableAccountID(v *int64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *GrsaiSettlementUpdate) AddAccountID(v int64) *GrsaiSettlementUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GrsaiSettlementUpdate) SetGroupID(v int64) *GrsaiSettlementUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableGroupID(v *int64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GrsaiSettlementUpdate) AddGroupID(v int64) *GrsaiSettlementUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GrsaiSettlementUpdate) SetUserID(v int64) *GrsaiSettlementUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableUserID(v *int64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GrsaiSettlementUpdate) AddUserID(v int64) *GrsaiSettlementUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *GrsaiSettlementUpdate) SetAPIKeyID(v int64) *GrsaiSettlementUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableAPIKeyID(v *int64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *GrsaiSettlementUpdate) AddAPIKeyID(v int64) *GrsaiSettlementUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *GrsaiSettlementUpdate) SetModel(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableModel(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetBaseUnitPrice sets the "base_unit_price" field.
func (_u *GrsaiSettlementUpdate) SetBaseUnitPrice(v float64) *GrsaiSettlementUpdate {
	_u.mutation.ResetBaseUnitPrice()
	_u.mutation.SetBaseUnitPrice(v)
	return _u
}

// SetNillableBaseUnitPrice sets the "base_unit_price" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableBaseUnitPrice(v *float64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetBaseUnitPrice(*v)
	}
	return _u
}

// AddBaseUnitPrice adds value to the "base_unit_price" field.
func (_u *GrsaiSettlementUpdate) AddBaseUnitPrice(v float64) *GrsaiSettlementUpdate {
	_u.mutation.AddBaseUnitPrice(v)
	return _u
}

// SetGroupRateMultiplier sets the "group_rate_multiplier" field.
func (_u *GrsaiSettlementUpdate) SetGroupRateMultiplier(v float64) *GrsaiSettlementUpdate {
	_u.mutation.ResetGroupRateMultiplier()
	_u.mutation.SetGroupRateMultiplier(v)
	return _u
}

// SetNillableGroupRateMultiplier sets the "group_rate_multiplier" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableGroupRateMultiplier(v *float64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetGroupRateMultiplier(*v)
	}
	return _u
}

// AddGroupRateMultiplier adds value to the "group_rate_multiplier" field.
func (_u *GrsaiSettlementUpdate) AddGroupRateMultiplier(v float64) *GrsaiSettlementUpdate {
	_u.mutation.AddGroupRateMultiplier(v)
	return _u
}

// SetAccountRateMultiplier sets the "account_rate_multiplier" field.
func (_u *GrsaiSettlementUpdate) SetAccountRateMultiplier(v float64) *GrsaiSettlementUpdate {
	_u.mutation.ResetAccountRateMultiplier()
	_u.mutation.SetAccountRateMultiplier(v)
	return _u
}

// SetNillableAccountRateMultiplier sets the "account_rate_multiplier" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableAccountRateMultiplier(v *float64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetAccountRateMultiplier(*v)
	}
	return _u
}

// AddAccountRateMultiplier adds value to the "account_rate_multiplier" field.
func (_u *GrsaiSettlementUpdate) AddAccountRateMultiplier(v float64) *GrsaiSettlementUpdate {
	_u.mutation.AddAccountRateMultiplier(v)
	return _u
}

// SetBillableUnitPrice sets the "billable_unit_price" field.
func (_u *GrsaiSettlementUpdate) SetBillableUnitPrice(v float64) *GrsaiSettlementUpdate {
	_u.mutation.ResetBillableUnitPrice()
	_u.mutation.SetBillableUnitPrice(v)
	return _u
}

// SetNillableBillableUnitPrice sets the "billable_unit_price" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableBillableUnitPrice(v *float64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetBillableUnitPrice(*v)
	}
	return _u
}

// AddBillableUnitPrice adds value to the "billable_unit_price" field.
func (_u *GrsaiSettlementUpdate) AddBillableUnitPrice(v float64) *GrsaiSettlementUpdate {
	_u.mutation.AddBillableUnitPrice(v)
	return _u
}

// SetRequestedImageCount sets the "requested_image_count" field.
func (_u *GrsaiSettlementUpdate) SetRequestedImageCount(v int) *GrsaiSettlementUpdate {
	_u.mutation.ResetRequestedImageCount()
	_u.mutation.SetRequestedImageCount(v)
	return _u
}

// SetNillableRequestedImageCount sets the "requested_image_count" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableRequestedImageCount(v *int) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetRequestedImageCount(*v)
	}
	return _u
}

// AddRequestedImageCount adds value to the "requested_image_count" field.
func (_u *GrsaiSettlementUpdate) AddRequestedImageCount(v int) *GrsaiSettlementUpdate {
	_u.mutation.AddRequestedImageCount(v)
	return _u
}

// SetMediaKind sets the "media_kind" field.
func (_u *GrsaiSettlementUpdate) SetMediaKind(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetMediaKind(v)
	return _u
}

// SetNillableMediaKind sets the "media_kind" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableMediaKind(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetMediaKind(*v)
	}
	return _u
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_u *GrsaiSettlementUpdate) SetVideoDurationSeconds(v int) *GrsaiSettlementUpdate {
	_u.mutation.ResetVideoDurationSeconds()
	_u.mutation.SetVideoDurationSeconds(v)
	return _u
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableVideoDurationSeconds(v *int) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetVideoDurationSeconds(*v)
	}
	return _u
}

// AddVideoDurationSeconds adds value to the "video_duration_seconds" field.
func (_u *GrsaiSettlementUpdate) AddVideoDurationSeconds(v int) *GrsaiSettlementUpdate {
	_u.mutation.AddVideoDurationSeconds(v)
	return _u
}

// SetVideoResolution sets the "video_resolution" field.
func (_u *GrsaiSettlementUpdate) SetVideoResolution(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetVideoResolution(v)
	return _u
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableVideoResolution(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetVideoResolution(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *GrsaiSettlementUpdate) SetCurrency(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableCurrency(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *GrsaiSettlementUpdate) SetUpstreamTaskID(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableUpstreamTaskID(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *GrsaiSettlementUpdate) ClearUpstreamTaskID() *GrsaiSettlementUpdate {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *GrsaiSettlementUpdate) SetUpstreamStatus(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableUpstreamStatus(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// SetInternalStatus sets the "internal_status" field.
func (_u *GrsaiSettlementUpdate) SetInternalStatus(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetInternalStatus(v)
	return _u
}

// SetNillableInternalStatus sets the "internal_status" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableInternalStatus(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetInternalStatus(*v)
	}
	return _u
}

// SetLocalTaskID sets the "local_task_id" field.
func (_u *GrsaiSettlementUpdate) SetLocalTaskID(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetLocalTaskID(v)
	return _u
}

// SetNillableLocalTaskID sets the "local_task_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableLocalTaskID(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetLocalTaskID(*v)
	}
	return _u
}

// ClearLocalTaskID clears the value of the "local_task_id" field.
func (_u *GrsaiSettlementUpdate) ClearLocalTaskID() *GrsaiSettlementUpdate {
	_u.mutation.ClearLocalTaskID()
	return _u
}

// SetDeliveryMode sets the "delivery_mode" field.
func (_u *GrsaiSettlementUpdate) SetDeliveryMode(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetDeliveryMode(v)
	return _u
}

// SetNillableDeliveryMode sets the "delivery_mode" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableDeliveryMode(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetDeliveryMode(*v)
	}
	return _u
}

// SetPublicStatus sets the "public_status" field.
func (_u *GrsaiSettlementUpdate) SetPublicStatus(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetPublicStatus(v)
	return _u
}

// SetNillablePublicStatus sets the "public_status" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillablePublicStatus(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetPublicStatus(*v)
	}
	return _u
}

// SetProgress sets the "progress" field.
func (_u *GrsaiSettlementUpdate) SetProgress(v int) *GrsaiSettlementUpdate {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableProgress(v *int) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *GrsaiSettlementUpdate) AddProgress(v int) *GrsaiSettlementUpdate {
	_u.mutation.AddProgress(v)
	return _u
}

// SetResultJSON sets the "result_json" field.
func (_u *GrsaiSettlementUpdate) SetResultJSON(v jsontext.Value) *GrsaiSettlementUpdate {
	_u.mutation.SetResultJSON(v)
	return _u
}

// AppendResultJSON appends value to the "result_json" field.
func (_u *GrsaiSettlementUpdate) AppendResultJSON(v jsontext.Value) *GrsaiSettlementUpdate {
	_u.mutation.AppendResultJSON(v)
	return _u
}

// ClearResultJSON clears the value of the "result_json" field.
func (_u *GrsaiSettlementUpdate) ClearResultJSON() *GrsaiSettlementUpdate {
	_u.mutation.ClearResultJSON()
	return _u
}

// SetLinkExpiresAt sets the "link_expires_at" field.
func (_u *GrsaiSettlementUpdate) SetLinkExpiresAt(v time.Time) *GrsaiSettlementUpdate {
	_u.mutation.SetLinkExpiresAt(v)
	return _u
}

// SetNillableLinkExpiresAt sets the "link_expires_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableLinkExpiresAt(v *time.Time) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetLinkExpiresAt(*v)
	}
	return _u
}

// ClearLinkExpiresAt clears the value of the "link_expires_at" field.
func (_u *GrsaiSettlementUpdate) ClearLinkExpiresAt() *GrsaiSettlementUpdate {
	_u.mutation.ClearLinkExpiresAt()
	return _u
}

// SetImageObjectMetadata sets the "image_object_metadata" field.
func (_u *GrsaiSettlementUpdate) SetImageObjectMetadata(v jsontext.Value) *GrsaiSettlementUpdate {
	_u.mutation.SetImageObjectMetadata(v)
	return _u
}

// AppendImageObjectMetadata appends value to the "image_object_metadata" field.
func (_u *GrsaiSettlementUpdate) AppendImageObjectMetadata(v jsontext.Value) *GrsaiSettlementUpdate {
	_u.mutation.AppendImageObjectMetadata(v)
	return _u
}

// ClearImageObjectMetadata clears the value of the "image_object_metadata" field.
func (_u *GrsaiSettlementUpdate) ClearImageObjectMetadata() *GrsaiSettlementUpdate {
	_u.mutation.ClearImageObjectMetadata()
	return _u
}

// SetTaskVersion sets the "task_version" field.
func (_u *GrsaiSettlementUpdate) SetTaskVersion(v int) *GrsaiSettlementUpdate {
	_u.mutation.ResetTaskVersion()
	_u.mutation.SetTaskVersion(v)
	return _u
}

// SetNillableTaskVersion sets the "task_version" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableTaskVersion(v *int) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetTaskVersion(*v)
	}
	return _u
}

// AddTaskVersion adds value to the "task_version" field.
func (_u *GrsaiSettlementUpdate) AddTaskVersion(v int) *GrsaiSettlementUpdate {
	_u.mutation.AddTaskVersion(v)
	return _u
}

// SetSubmissionAttempt sets the "submission_attempt" field.
func (_u *GrsaiSettlementUpdate) SetSubmissionAttempt(v int) *GrsaiSettlementUpdate {
	_u.mutation.ResetSubmissionAttempt()
	_u.mutation.SetSubmissionAttempt(v)
	return _u
}

// SetNillableSubmissionAttempt sets the "submission_attempt" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableSubmissionAttempt(v *int) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetSubmissionAttempt(*v)
	}
	return _u
}

// AddSubmissionAttempt adds value to the "submission_attempt" field.
func (_u *GrsaiSettlementUpdate) AddSubmissionAttempt(v int) *GrsaiSettlementUpdate {
	_u.mutation.AddSubmissionAttempt(v)
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *GrsaiSettlementUpdate) SetRetryCount(v int) *GrsaiSettlementUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableRetryCount(v *int) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *GrsaiSettlementUpdate) AddRetryCount(v int) *GrsaiSettlementUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetSettlementRetryCount sets the "settlement_retry_count" field.
func (_u *GrsaiSettlementUpdate) SetSettlementRetryCount(v int) *GrsaiSettlementUpdate {
	_u.mutation.ResetSettlementRetryCount()
	_u.mutation.SetSettlementRetryCount(v)
	return _u
}

// SetNillableSettlementRetryCount sets the "settlement_retry_count" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableSettlementRetryCount(v *int) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetSettlementRetryCount(*v)
	}
	return _u
}

// AddSettlementRetryCount adds value to the "settlement_retry_count" field.
func (_u *GrsaiSettlementUpdate) AddSettlementRetryCount(v int) *GrsaiSettlementUpdate {
	_u.mutation.AddSettlementRetryCount(v)
	return _u
}

// SetClaimVersion sets the "claim_version" field.
func (_u *GrsaiSettlementUpdate) SetClaimVersion(v int64) *GrsaiSettlementUpdate {
	_u.mutation.ResetClaimVersion()
	_u.mutation.SetClaimVersion(v)
	return _u
}

// SetNillableClaimVersion sets the "claim_version" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableClaimVersion(v *int64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetClaimVersion(*v)
	}
	return _u
}

// AddClaimVersion adds value to the "claim_version" field.
func (_u *GrsaiSettlementUpdate) AddClaimVersion(v int64) *GrsaiSettlementUpdate {
	_u.mutation.AddClaimVersion(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *GrsaiSettlementUpdate) SetNextAttemptAt(v time.Time) *GrsaiSettlementUpdate {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableNextAttemptAt(v *time.Time) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetLastErrorSummary sets the "last_error_summary" field.
func (_u *GrsaiSettlementUpdate) SetLastErrorSummary(v string) *GrsaiSettlementUpdate {
	_u.mutation.SetLastErrorSummary(v)
	return _u
}

// SetNillableLastErrorSummary sets the "last_error_summary" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableLastErrorSummary(v *string) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetLastErrorSummary(*v)
	}
	return _u
}

// ClearLastErrorSummary clears the value of the "last_error_summary" field.
func (_u *GrsaiSettlementUpdate) ClearLastErrorSummary() *GrsaiSettlementUpdate {
	_u.mutation.ClearLastErrorSummary()
	return _u
}

// SetSettledAmount sets the "settled_amount" field.
func (_u *GrsaiSettlementUpdate) SetSettledAmount(v float64) *GrsaiSettlementUpdate {
	_u.mutation.ResetSettledAmount()
	_u.mutation.SetSettledAmount(v)
	return _u
}

// SetNillableSettledAmount sets the "settled_amount" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableSettledAmount(v *float64) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetSettledAmount(*v)
	}
	return _u
}

// AddSettledAmount adds value to the "settled_amount" field.
func (_u *GrsaiSettlementUpdate) AddSettledAmount(v float64) *GrsaiSettlementUpdate {
	_u.mutation.AddSettledAmount(v)
	return _u
}

// ClearSettledAmount clears the value of the "settled_amount" field.
func (_u *GrsaiSettlementUpdate) ClearSettledAmount() *GrsaiSettlementUpdate {
	_u.mutation.ClearSettledAmount()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GrsaiSettlementUpdate) SetUpdatedAt(v time.Time) *GrsaiSettlementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpstreamBoundAt sets the "upstream_bound_at" field.
func (_u *GrsaiSettlementUpdate) SetUpstreamBoundAt(v time.Time) *GrsaiSettlementUpdate {
	_u.mutation.SetUpstreamBoundAt(v)
	return _u
}

// SetNillableUpstreamBoundAt sets the "upstream_bound_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableUpstreamBoundAt(v *time.Time) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetUpstreamBoundAt(*v)
	}
	return _u
}

// ClearUpstreamBoundAt clears the value of the "upstream_bound_at" field.
func (_u *GrsaiSettlementUpdate) ClearUpstreamBoundAt() *GrsaiSettlementUpdate {
	_u.mutation.ClearUpstreamBoundAt()
	return _u
}

// SetResultUpdatedAt sets the "result_updated_at" field.
func (_u *GrsaiSettlementUpdate) SetResultUpdatedAt(v time.Time) *GrsaiSettlementUpdate {
	_u.mutation.SetResultUpdatedAt(v)
	return _u
}

// SetNillableResultUpdatedAt sets the "result_updated_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableResultUpdatedAt(v *time.Time) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetResultUpdatedAt(*v)
	}
	return _u
}

// ClearResultUpdatedAt clears the value of the "result_updated_at" field.
func (_u *GrsaiSettlementUpdate) ClearResultUpdatedAt() *GrsaiSettlementUpdate {
	_u.mutation.ClearResultUpdatedAt()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *GrsaiSettlementUpdate) SetSettledAt(v time.Time) *GrsaiSettlementUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableSettledAt(v *time.Time) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *GrsaiSettlementUpdate) ClearSettledAt() *GrsaiSettlementUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *GrsaiSettlementUpdate) SetClosedAt(v time.Time) *GrsaiSettlementUpdate {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdate) SetNillableClosedAt(v *time.Time) *GrsaiSettlementUpdate {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *GrsaiSettlementUpdate) ClearClosedAt() *GrsaiSettlementUpdate {
	_u.mutation.ClearClosedAt()
	return _u
}

// Mutation returns the GrsaiSettlementMutation object of the builder.
func (_u *GrsaiSettlementUpdate) Mutation() *GrsaiSettlementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GrsaiSettlementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrsaiSettlementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GrsaiSettlementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrsaiSettlementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GrsaiSettlementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grsaisettlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GrsaiSettlementUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := grsaisettlement.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaKind(); ok {
		if err := grsaisettlement.MediaKindValidator(v); err != nil {
			return &ValidationError{Name: "media_kind", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.media_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VideoResolution(); ok {
		if err := grsaisettlement.VideoResolutionValidator(v); err != nil {
			return &ValidationError{Name: "video_resolution", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.video_resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := grsaisettlement.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := grsaisettlement.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamStatus(); ok {
		if err := grsaisettlement.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.upstream_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InternalStatus(); ok {
		if err := grsaisettlement.InternalStatusValidator(v); err != nil {
			return &ValidationError{Name: "internal_status", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.internal_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalTaskID(); ok {
		if err := grsaisettlement.LocalTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "local_task_id", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.local_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryMode(); ok {
		if err := grsaisettlement.DeliveryModeValidator(v); err != nil {
			return &ValidationError{Name: "delivery_mode", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.delivery_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicStatus(); ok {
		if err := grsaisettlement.PublicStatusValidator(v); err != nil {
			return &ValidationError{Name: "public_status", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.public_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorSummary(); ok {
		if err := grsaisettlement.LastErrorSummaryValidator(v); err != nil {
			return &ValidationError{Name: "last_error_summary", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.last_error_summary": %w`, err)}
		}
	}
	return nil
}

func (_u *GrsaiSettlementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grsaisettlement.Table, grsaisettlement.Columns, sqlgraph.NewFieldSpec(grsaisettlement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(grsaisettlement.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(grsaisettlement.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(grsaisettlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(grsaisettlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(grsaisettlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(grsaisettlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(grsaisettlement.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(grsaisettlement.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(grsaisettlement.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseUnitPrice(); ok {
		_spec.SetField(grsaisettlement.FieldBaseUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseUnitPrice(); ok {
		_spec.AddField(grsaisettlement.FieldBaseUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GroupRateMultiplier(); ok {
		_spec.SetField(grsaisettlement.FieldGroupRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGroupRateMultiplier(); ok {
		_spec.AddField(grsaisettlement.FieldGroupRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AccountRateMultiplier(); ok {
		_spec.SetField(grsaisettlement.FieldAccountRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAccountRateMultiplier(); ok {
		_spec.AddField(grsaisettlement.FieldAccountRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BillableUnitPrice(); ok {
		_spec.SetField(grsaisettlement.FieldBillableUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBillableUnitPrice(); ok {
		_spec.AddField(grsaisettlement.FieldBillableUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RequestedImageCount(); ok {
		_spec.SetField(grsaisettlement.FieldRequestedImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestedImageCount(); ok {
		_spec.AddField(grsaisettlement.FieldRequestedImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MediaKind(); ok {
		_spec.SetField(grsaisettlement.FieldMediaKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(grsaisettlement.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoDurationSeconds(); ok {
		_spec.AddField(grsaisettlement.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VideoResolution(); ok {
		_spec.SetField(grsaisettlement.FieldVideoResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(grsaisettlement.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(grsaisettlement.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(grsaisettlement.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(grsaisettlement.FieldUpstreamStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InternalStatus(); ok {
		_spec.SetField(grsaisettlement.FieldInternalStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalTaskID(); ok {
		_spec.SetField(grsaisettlement.FieldLocalTaskID, field.TypeString, value)
	}
	if _u.mutation.LocalTaskIDCleared() {
		_spec.ClearField(grsaisettlement.FieldLocalTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveryMode(); ok {
		_spec.SetField(grsaisettlement.FieldDeliveryMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicStatus(); ok {
		_spec.SetField(grsaisettlement.FieldPublicStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(grsaisettlement.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(grsaisettlement.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResultJSON(); ok {
		_spec.SetField(grsaisettlement.FieldResultJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResultJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, grsaisettlement.FieldResultJSON, value)
		})
	}
	if _u.mutation.ResultJSONCleared() {
		_spec.ClearField(grsaisettlement.FieldResultJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.LinkExpiresAt(); ok {
		_spec.SetField(grsaisettlement.FieldLinkExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LinkExpiresAtCleared() {
		_spec.ClearField(grsaisettlement.FieldLinkExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ImageObjectMetadata(); ok {
		_spec.SetField(grsaisettlement.FieldImageObjectMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImageObjectMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, grsaisettlement.FieldImageObjectMetadata, value)
		})
	}
	if _u.mutation.ImageObjectMetadataCleared() {
		_spec.ClearField(grsaisettlement.FieldImageObjectMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.TaskVersion(); ok {
		_spec.SetField(grsaisettlement.FieldTaskVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTaskVersion(); ok {
		_spec.AddField(grsaisettlement.FieldTaskVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SubmissionAttempt(); ok {
		_spec.SetField(grsaisettlement.FieldSubmissionAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSubmissionAttempt(); ok {
		_spec.AddField(grsaisettlement.FieldSubmissionAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(grsaisettlement.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(grsaisettlement.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettlementRetryCount(); ok {
		_spec.SetField(grsaisettlement.FieldSettlementRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettlementRetryCount(); ok {
		_spec.AddField(grsaisettlement.FieldSettlementRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClaimVersion(); ok {
		_spec.SetField(grsaisettlement.FieldClaimVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClaimVersion(); ok {
		_spec.AddField(grsaisettlement.FieldClaimVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(grsaisettlement.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastErrorSummary(); ok {
		_spec.SetField(grsaisettlement.FieldLastErrorSummary, field.TypeString, value)
	}
	if _u.mutation.LastErrorSummaryCleared() {
		_spec.ClearField(grsaisettlement.FieldLastErrorSummary, field.TypeString)
	}
	if value, ok := _u.mutation.SettledAmount(); ok {
		_spec.SetField(grsaisettlement.FieldSettledAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledAmount(); ok {
		_spec.AddField(grsaisettlement.FieldSettledAmount, field.TypeFloat64, value)
	}
	if _u.mutation.SettledAmountCleared() {
		_spec.ClearField(grsaisettlement.FieldSettledAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grsaisettlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpstreamBoundAt(); ok {
		_spec.SetField(grsaisettlement.FieldUpstreamBoundAt, field.TypeTime, value)
	}
	if _u.mutation.UpstreamBoundAtCleared() {
		_spec.ClearField(grsaisettlement.FieldUpstreamBoundAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResultUpdatedAt(); ok {
		_spec.SetField(grsaisettlement.FieldResultUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ResultUpdatedAtCleared() {
		_spec.ClearField(grsaisettlement.FieldResultUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(grsaisettlement.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(grsaisettlement.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(grsaisettlement.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(grsaisettlement.FieldClosedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grsaisettlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GrsaiSettlementUpdateOne is the builder for updating a single GrsaiSettlement entity.
type GrsaiSettlementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GrsaiSettlementMutation
}

// SetAccountID sets the "account_id" field.
func (_u *GrsaiSettlementUpdateOne) SetAccountID(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableAccountID(v *int64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *GrsaiSettlementUpdateOne) AddAccountID(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *GrsaiSettlementUpdateOne) SetGroupID(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableGroupID(v *int64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *GrsaiSettlementUpdateOne) AddGroupID(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GrsaiSettlementUpdateOne) SetUserID(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableUserID(v *int64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *GrsaiSettlementUpdateOne) AddUserID(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *GrsaiSettlementUpdateOne) SetAPIKeyID(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableAPIKeyID(v *int64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *GrsaiSettlementUpdateOne) AddAPIKeyID(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *GrsaiSettlementUpdateOne) SetModel(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableModel(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetBaseUnitPrice sets the "base_unit_price" field.
func (_u *GrsaiSettlementUpdateOne) SetBaseUnitPrice(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetBaseUnitPrice()
	_u.mutation.SetBaseUnitPrice(v)
	return _u
}

// SetNillableBaseUnitPrice sets the "base_unit_price" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableBaseUnitPrice(v *float64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetBaseUnitPrice(*v)
	}
	return _u
}

// AddBaseUnitPrice adds value to the "base_unit_price" field.
func (_u *GrsaiSettlementUpdateOne) AddBaseUnitPrice(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddBaseUnitPrice(v)
	return _u
}

// SetGroupRateMultiplier sets the "group_rate_multiplier" field.
func (_u *GrsaiSettlementUpdateOne) SetGroupRateMultiplier(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetGroupRateMultiplier()
	_u.mutation.SetGroupRateMultiplier(v)
	return _u
}

// SetNillableGroupRateMultiplier sets the "group_rate_multiplier" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableGroupRateMultiplier(v *float64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetGroupRateMultiplier(*v)
	}
	return _u
}

// AddGroupRateMultiplier adds value to the "group_rate_multiplier" field.
func (_u *GrsaiSettlementUpdateOne) AddGroupRateMultiplier(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddGroupRateMultiplier(v)
	return _u
}

// SetAccountRateMultiplier sets the "account_rate_multiplier" field.
func (_u *GrsaiSettlementUpdateOne) SetAccountRateMultiplier(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetAccountRateMultiplier()
	_u.mutation.SetAccountRateMultiplier(v)
	return _u
}

// SetNillableAccountRateMultiplier sets the "account_rate_multiplier" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableAccountRateMultiplier(v *float64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetAccountRateMultiplier(*v)
	}
	return _u
}

// AddAccountRateMultiplier adds value to the "account_rate_multiplier" field.
func (_u *GrsaiSettlementUpdateOne) AddAccountRateMultiplier(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddAccountRateMultiplier(v)
	return _u
}

// SetBillableUnitPrice sets the "billable_unit_price" field.
func (_u *GrsaiSettlementUpdateOne) SetBillableUnitPrice(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetBillableUnitPrice()
	_u.mutation.SetBillableUnitPrice(v)
	return _u
}

// SetNillableBillableUnitPrice sets the "billable_unit_price" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableBillableUnitPrice(v *float64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetBillableUnitPrice(*v)
	}
	return _u
}

// AddBillableUnitPrice adds value to the "billable_unit_price" field.
func (_u *GrsaiSettlementUpdateOne) AddBillableUnitPrice(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddBillableUnitPrice(v)
	return _u
}

// SetRequestedImageCount sets the "requested_image_count" field.
func (_u *GrsaiSettlementUpdateOne) SetRequestedImageCount(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetRequestedImageCount()
	_u.mutation.SetRequestedImageCount(v)
	return _u
}

// SetNillableRequestedImageCount sets the "requested_image_count" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableRequestedImageCount(v *int) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetRequestedImageCount(*v)
	}
	return _u
}

// AddRequestedImageCount adds value to the "requested_image_count" field.
func (_u *GrsaiSettlementUpdateOne) AddRequestedImageCount(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.AddRequestedImageCount(v)
	return _u
}

// SetMediaKind sets the "media_kind" field.
func (_u *GrsaiSettlementUpdateOne) SetMediaKind(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetMediaKind(v)
	return _u
}

// SetNillableMediaKind sets the "media_kind" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableMediaKind(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetMediaKind(*v)
	}
	return _u
}

// SetVideoDurationSeconds sets the "video_duration_seconds" field.
func (_u *GrsaiSettlementUpdateOne) SetVideoDurationSeconds(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetVideoDurationSeconds()
	_u.mutation.SetVideoDurationSeconds(v)
	return _u
}

// SetNillableVideoDurationSeconds sets the "video_duration_seconds" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableVideoDurationSeconds(v *int) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetVideoDurationSeconds(*v)
	}
	return _u
}

// AddVideoDurationSeconds adds value to the "video_duration_seconds" field.
func (_u *GrsaiSettlementUpdateOne) AddVideoDurationSeconds(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.AddVideoDurationSeconds(v)
	return _u
}

// SetVideoResolution sets the "video_resolution" field.
func (_u *GrsaiSettlementUpdateOne) SetVideoResolution(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetVideoResolution(v)
	return _u
}

// SetNillableVideoResolution sets the "video_resolution" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableVideoResolution(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetVideoResolution(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *GrsaiSettlementUpdateOne) SetCurrency(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableCurrency(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetUpstreamTaskID sets the "upstream_task_id" field.
func (_u *GrsaiSettlementUpdateOne) SetUpstreamTaskID(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetUpstreamTaskID(v)
	return _u
}

// SetNillableUpstreamTaskID sets the "upstream_task_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableUpstreamTaskID(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetUpstreamTaskID(*v)
	}
	return _u
}

// ClearUpstreamTaskID clears the value of the "upstream_task_id" field.
func (_u *GrsaiSettlementUpdateOne) ClearUpstreamTaskID() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearUpstreamTaskID()
	return _u
}

// SetUpstreamStatus sets the "upstream_status" field.
func (_u *GrsaiSettlementUpdateOne) SetUpstreamStatus(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetUpstreamStatus(v)
	return _u
}

// SetNillableUpstreamStatus sets the "upstream_status" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableUpstreamStatus(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetUpstreamStatus(*v)
	}
	return _u
}

// SetInternalStatus sets the "internal_status" field.
func (_u *GrsaiSettlementUpdateOne) SetInternalStatus(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetInternalStatus(v)
	return _u
}

// SetNillableInternalStatus sets the "internal_status" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableInternalStatus(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetInternalStatus(*v)
	}
	return _u
}

// SetLocalTaskID sets the "local_task_id" field.
func (_u *GrsaiSettlementUpdateOne) SetLocalTaskID(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetLocalTaskID(v)
	return _u
}

// SetNillableLocalTaskID sets the "local_task_id" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableLocalTaskID(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetLocalTaskID(*v)
	}
	return _u
}

// ClearLocalTaskID clears the value of the "local_task_id" field.
func (_u *GrsaiSettlementUpdateOne) ClearLocalTaskID() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearLocalTaskID()
	return _u
}

// SetDeliveryMode sets the "delivery_mode" field.
func (_u *GrsaiSettlementUpdateOne) SetDeliveryMode(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetDeliveryMode(v)
	return _u
}

// SetNillableDeliveryMode sets the "delivery_mode" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableDeliveryMode(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetDeliveryMode(*v)
	}
	return _u
}

// SetPublicStatus sets the "public_status" field.
func (_u *GrsaiSettlementUpdateOne) SetPublicStatus(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetPublicStatus(v)
	return _u
}

// SetNillablePublicStatus sets the "public_status" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillablePublicStatus(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetPublicStatus(*v)
	}
	return _u
}

// SetProgress sets the "progress" field.
func (_u *GrsaiSettlementUpdateOne) SetProgress(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetProgress()
	_u.mutation.SetProgress(v)
	return _u
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableProgress(v *int) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetProgress(*v)
	}
	return _u
}

// AddProgress adds value to the "progress" field.
func (_u *GrsaiSettlementUpdateOne) AddProgress(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.AddProgress(v)
	return _u
}

// SetResultJSON sets the "result_json" field.
func (_u *GrsaiSettlementUpdateOne) SetResultJSON(v jsontext.Value) *GrsaiSettlementUpdateOne {
	_u.mutation.SetResultJSON(v)
	return _u
}

// AppendResultJSON appends value to the "result_json" field.
func (_u *GrsaiSettlementUpdateOne) AppendResultJSON(v jsontext.Value) *GrsaiSettlementUpdateOne {
	_u.mutation.AppendResultJSON(v)
	return _u
}

// ClearResultJSON clears the value of the "result_json" field.
func (_u *GrsaiSettlementUpdateOne) ClearResultJSON() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearResultJSON()
	return _u
}

// SetLinkExpiresAt sets the "link_expires_at" field.
func (_u *GrsaiSettlementUpdateOne) SetLinkExpiresAt(v time.Time) *GrsaiSettlementUpdateOne {
	_u.mutation.SetLinkExpiresAt(v)
	return _u
}

// SetNillableLinkExpiresAt sets the "link_expires_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableLinkExpiresAt(v *time.Time) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetLinkExpiresAt(*v)
	}
	return _u
}

// ClearLinkExpiresAt clears the value of the "link_expires_at" field.
func (_u *GrsaiSettlementUpdateOne) ClearLinkExpiresAt() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearLinkExpiresAt()
	return _u
}

// SetImageObjectMetadata sets the "image_object_metadata" field.
func (_u *GrsaiSettlementUpdateOne) SetImageObjectMetadata(v jsontext.Value) *GrsaiSettlementUpdateOne {
	_u.mutation.SetImageObjectMetadata(v)
	return _u
}

// AppendImageObjectMetadata appends value to the "image_object_metadata" field.
func (_u *GrsaiSettlementUpdateOne) AppendImageObjectMetadata(v jsontext.Value) *GrsaiSettlementUpdateOne {
	_u.mutation.AppendImageObjectMetadata(v)
	return _u
}

// ClearImageObjectMetadata clears the value of the "image_object_metadata" field.
func (_u *GrsaiSettlementUpdateOne) ClearImageObjectMetadata() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearImageObjectMetadata()
	return _u
}

// SetTaskVersion sets the "task_version" field.
func (_u *GrsaiSettlementUpdateOne) SetTaskVersion(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetTaskVersion()
	_u.mutation.SetTaskVersion(v)
	return _u
}

// SetNillableTaskVersion sets the "task_version" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableTaskVersion(v *int) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetTaskVersion(*v)
	}
	return _u
}

// AddTaskVersion adds value to the "task_version" field.
func (_u *GrsaiSettlementUpdateOne) AddTaskVersion(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.AddTaskVersion(v)
	return _u
}

// SetSubmissionAttempt sets the "submission_attempt" field.
func (_u *GrsaiSettlementUpdateOne) SetSubmissionAttempt(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetSubmissionAttempt()
	_u.mutation.SetSubmissionAttempt(v)
	return _u
}

// SetNillableSubmissionAttempt sets the "submission_attempt" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableSubmissionAttempt(v *int) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetSubmissionAttempt(*v)
	}
	return _u
}

// AddSubmissionAttempt adds value to the "submission_attempt" field.
func (_u *GrsaiSettlementUpdateOne) AddSubmissionAttempt(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.AddSubmissionAttempt(v)
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *GrsaiSettlementUpdateOne) SetRetryCount(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableRetryCount(v *int) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *GrsaiSettlementUpdateOne) AddRetryCount(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetSettlementRetryCount sets the "settlement_retry_count" field.
func (_u *GrsaiSettlementUpdateOne) SetSettlementRetryCount(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetSettlementRetryCount()
	_u.mutation.SetSettlementRetryCount(v)
	return _u
}

// SetNillableSettlementRetryCount sets the "settlement_retry_count" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableSettlementRetryCount(v *int) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetSettlementRetryCount(*v)
	}
	return _u
}

// AddSettlementRetryCount adds value to the "settlement_retry_count" field.
func (_u *GrsaiSettlementUpdateOne) AddSettlementRetryCount(v int) *GrsaiSettlementUpdateOne {
	_u.mutation.AddSettlementRetryCount(v)
	return _u
}

// SetClaimVersion sets the "claim_version" field.
func (_u *GrsaiSettlementUpdateOne) SetClaimVersion(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetClaimVersion()
	_u.mutation.SetClaimVersion(v)
	return _u
}

// SetNillableClaimVersion sets the "claim_version" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableClaimVersion(v *int64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetClaimVersion(*v)
	}
	return _u
}

// AddClaimVersion adds value to the "claim_version" field.
func (_u *GrsaiSettlementUpdateOne) AddClaimVersion(v int64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddClaimVersion(v)
	return _u
}

// SetNextAttemptAt sets the "next_attempt_at" field.
func (_u *GrsaiSettlementUpdateOne) SetNextAttemptAt(v time.Time) *GrsaiSettlementUpdateOne {
	_u.mutation.SetNextAttemptAt(v)
	return _u
}

// SetNillableNextAttemptAt sets the "next_attempt_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableNextAttemptAt(v *time.Time) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetNextAttemptAt(*v)
	}
	return _u
}

// SetLastErrorSummary sets the "last_error_summary" field.
func (_u *GrsaiSettlementUpdateOne) SetLastErrorSummary(v string) *GrsaiSettlementUpdateOne {
	_u.mutation.SetLastErrorSummary(v)
	return _u
}

// SetNillableLastErrorSummary sets the "last_error_summary" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableLastErrorSummary(v *string) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetLastErrorSummary(*v)
	}
	return _u
}

// ClearLastErrorSummary clears the value of the "last_error_summary" field.
func (_u *GrsaiSettlementUpdateOne) ClearLastErrorSummary() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearLastErrorSummary()
	return _u
}

// SetSettledAmount sets the "settled_amount" field.
func (_u *GrsaiSettlementUpdateOne) SetSettledAmount(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.ResetSettledAmount()
	_u.mutation.SetSettledAmount(v)
	return _u
}

// SetNillableSettledAmount sets the "settled_amount" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableSettledAmount(v *float64) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetSettledAmount(*v)
	}
	return _u
}

// AddSettledAmount adds value to the "settled_amount" field.
func (_u *GrsaiSettlementUpdateOne) AddSettledAmount(v float64) *GrsaiSettlementUpdateOne {
	_u.mutation.AddSettledAmount(v)
	return _u
}

// ClearSettledAmount clears the value of the "settled_amount" field.
func (_u *GrsaiSettlementUpdateOne) ClearSettledAmount() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearSettledAmount()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GrsaiSettlementUpdateOne) SetUpdatedAt(v time.Time) *GrsaiSettlementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUpstreamBoundAt sets the "upstream_bound_at" field.
func (_u *GrsaiSettlementUpdateOne) SetUpstreamBoundAt(v time.Time) *GrsaiSettlementUpdateOne {
	_u.mutation.SetUpstreamBoundAt(v)
	return _u
}

// SetNillableUpstreamBoundAt sets the "upstream_bound_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableUpstreamBoundAt(v *time.Time) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetUpstreamBoundAt(*v)
	}
	return _u
}

// ClearUpstreamBoundAt clears the value of the "upstream_bound_at" field.
func (_u *GrsaiSettlementUpdateOne) ClearUpstreamBoundAt() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearUpstreamBoundAt()
	return _u
}

// SetResultUpdatedAt sets the "result_updated_at" field.
func (_u *GrsaiSettlementUpdateOne) SetResultUpdatedAt(v time.Time) *GrsaiSettlementUpdateOne {
	_u.mutation.SetResultUpdatedAt(v)
	return _u
}

// SetNillableResultUpdatedAt sets the "result_updated_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableResultUpdatedAt(v *time.Time) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetResultUpdatedAt(*v)
	}
	return _u
}

// ClearResultUpdatedAt clears the value of the "result_updated_at" field.
func (_u *GrsaiSettlementUpdateOne) ClearResultUpdatedAt() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearResultUpdatedAt()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *GrsaiSettlementUpdateOne) SetSettledAt(v time.Time) *GrsaiSettlementUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableSettledAt(v *time.Time) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *GrsaiSettlementUpdateOne) ClearSettledAt() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetClosedAt sets the "closed_at" field.
func (_u *GrsaiSettlementUpdateOne) SetClosedAt(v time.Time) *GrsaiSettlementUpdateOne {
	_u.mutation.SetClosedAt(v)
	return _u
}

// SetNillableClosedAt sets the "closed_at" field if the given value is not nil.
func (_u *GrsaiSettlementUpdateOne) SetNillableClosedAt(v *time.Time) *GrsaiSettlementUpdateOne {
	if v != nil {
		_u.SetClosedAt(*v)
	}
	return _u
}

// ClearClosedAt clears the value of the "closed_at" field.
func (_u *GrsaiSettlementUpdateOne) ClearClosedAt() *GrsaiSettlementUpdateOne {
	_u.mutation.ClearClosedAt()
	return _u
}

// Mutation returns the GrsaiSettlementMutation object of the builder.
func (_u *GrsaiSettlementUpdateOne) Mutation() *GrsaiSettlementMutation {
	return _u.mutation
}

// Where appends a list predicates to the GrsaiSettlementUpdate builder.
func (_u *GrsaiSettlementUpdateOne) Where(ps ...predicate.GrsaiSettlement) *GrsaiSettlementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GrsaiSettlementUpdateOne) Select(field string, fields ...string) *GrsaiSettlementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GrsaiSettlement entity.
func (_u *GrsaiSettlementUpdateOne) Save(ctx context.Context) (*GrsaiSettlement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GrsaiSettlementUpdateOne) SaveX(ctx context.Context) *GrsaiSettlement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GrsaiSettlementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GrsaiSettlementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GrsaiSettlementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := grsaisettlement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GrsaiSettlementUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := grsaisettlement.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MediaKind(); ok {
		if err := grsaisettlement.MediaKindValidator(v); err != nil {
			return &ValidationError{Name: "media_kind", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.media_kind": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VideoResolution(); ok {
		if err := grsaisettlement.VideoResolutionValidator(v); err != nil {
			return &ValidationError{Name: "video_resolution", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.video_resolution": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := grsaisettlement.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamTaskID(); ok {
		if err := grsaisettlement.UpstreamTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "upstream_task_id", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.upstream_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamStatus(); ok {
		if err := grsaisettlement.UpstreamStatusValidator(v); err != nil {
			return &ValidationError{Name: "upstream_status", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.upstream_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.InternalStatus(); ok {
		if err := grsaisettlement.InternalStatusValidator(v); err != nil {
			return &ValidationError{Name: "internal_status", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.internal_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LocalTaskID(); ok {
		if err := grsaisettlement.LocalTaskIDValidator(v); err != nil {
			return &ValidationError{Name: "local_task_id", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.local_task_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeliveryMode(); ok {
		if err := grsaisettlement.DeliveryModeValidator(v); err != nil {
			return &ValidationError{Name: "delivery_mode", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.delivery_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicStatus(); ok {
		if err := grsaisettlement.PublicStatusValidator(v); err != nil {
			return &ValidationError{Name: "public_status", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.public_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastErrorSummary(); ok {
		if err := grsaisettlement.LastErrorSummaryValidator(v); err != nil {
			return &ValidationError{Name: "last_error_summary", err: fmt.Errorf(`ent: validator failed for field "GrsaiSettlement.last_error_summary": %w`, err)}
		}
	}
	return nil
}

func (_u *GrsaiSettlementUpdateOne) sqlSave(ctx context.Context) (_node *GrsaiSettlement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(grsaisettlement.Table, grsaisettlement.Columns, sqlgraph.NewFieldSpec(grsaisettlement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GrsaiSettlement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, grsaisettlement.FieldID)
		for _, f := range fields {
			if !grsaisettlement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != grsaisettlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(grsaisettlement.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(grsaisettlement.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(grsaisettlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(grsaisettlement.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(grsaisettlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(grsaisettlement.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(grsaisettlement.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(grsaisettlement.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(grsaisettlement.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseUnitPrice(); ok {
		_spec.SetField(grsaisettlement.FieldBaseUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseUnitPrice(); ok {
		_spec.AddField(grsaisettlement.FieldBaseUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.GroupRateMultiplier(); ok {
		_spec.SetField(grsaisettlement.FieldGroupRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedGroupRateMultiplier(); ok {
		_spec.AddField(grsaisettlement.FieldGroupRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AccountRateMultiplier(); ok {
		_spec.SetField(grsaisettlement.FieldAccountRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAccountRateMultiplier(); ok {
		_spec.AddField(grsaisettlement.FieldAccountRateMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BillableUnitPrice(); ok {
		_spec.SetField(grsaisettlement.FieldBillableUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBillableUnitPrice(); ok {
		_spec.AddField(grsaisettlement.FieldBillableUnitPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RequestedImageCount(); ok {
		_spec.SetField(grsaisettlement.FieldRequestedImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequestedImageCount(); ok {
		_spec.AddField(grsaisettlement.FieldRequestedImageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MediaKind(); ok {
		_spec.SetField(grsaisettlement.FieldMediaKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.VideoDurationSeconds(); ok {
		_spec.SetField(grsaisettlement.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVideoDurationSeconds(); ok {
		_spec.AddField(grsaisettlement.FieldVideoDurationSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.VideoResolution(); ok {
		_spec.SetField(grsaisettlement.FieldVideoResolution, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(grsaisettlement.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamTaskID(); ok {
		_spec.SetField(grsaisettlement.FieldUpstreamTaskID, field.TypeString, value)
	}
	if _u.mutation.UpstreamTaskIDCleared() {
		_spec.ClearField(grsaisettlement.FieldUpstreamTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.UpstreamStatus(); ok {
		_spec.SetField(grsaisettlement.FieldUpstreamStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.InternalStatus(); ok {
		_spec.SetField(grsaisettlement.FieldInternalStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.LocalTaskID(); ok {
		_spec.SetField(grsaisettlement.FieldLocalTaskID, field.TypeString, value)
	}
	if _u.mutation.LocalTaskIDCleared() {
		_spec.ClearField(grsaisettlement.FieldLocalTaskID, field.TypeString)
	}
	if value, ok := _u.mutation.DeliveryMode(); ok {
		_spec.SetField(grsaisettlement.FieldDeliveryMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicStatus(); ok {
		_spec.SetField(grsaisettlement.FieldPublicStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Progress(); ok {
		_spec.SetField(grsaisettlement.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedProgress(); ok {
		_spec.AddField(grsaisettlement.FieldProgress, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResultJSON(); ok {
		_spec.SetField(grsaisettlement.FieldResultJSON, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResultJSON(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, grsaisettlement.FieldResultJSON, value)
		})
	}
	if _u.mutation.ResultJSONCleared() {
		_spec.ClearField(grsaisettlement.FieldResultJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.LinkExpiresAt(); ok {
		_spec.SetField(grsaisettlement.FieldLinkExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.LinkExpiresAtCleared() {
		_spec.ClearField(grsaisettlement.FieldLinkExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ImageObjectMetadata(); ok {
		_spec.SetField(grsaisettlement.FieldImageObjectMetadata, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedImageObjectMetadata(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, grsaisettlement.FieldImageObjectMetadata, value)
		})
	}
	if _u.mutation.ImageObjectMetadataCleared() {
		_spec.ClearField(grsaisettlement.FieldImageObjectMetadata, field.TypeJSON)
	}
	if value, ok := _u.mutation.TaskVersion(); ok {
		_spec.SetField(grsaisettlement.FieldTaskVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTaskVersion(); ok {
		_spec.AddField(grsaisettlement.FieldTaskVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SubmissionAttempt(); ok {
		_spec.SetField(grsaisettlement.FieldSubmissionAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSubmissionAttempt(); ok {
		_spec.AddField(grsaisettlement.FieldSubmissionAttempt, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(grsaisettlement.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(grsaisettlement.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SettlementRetryCount(); ok {
		_spec.SetField(grsaisettlement.FieldSettlementRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSettlementRetryCount(); ok {
		_spec.AddField(grsaisettlement.FieldSettlementRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClaimVersion(); ok {
		_spec.SetField(grsaisettlement.FieldClaimVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedClaimVersion(); ok {
		_spec.AddField(grsaisettlement.FieldClaimVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.NextAttemptAt(); ok {
		_spec.SetField(grsaisettlement.FieldNextAttemptAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastErrorSummary(); ok {
		_spec.SetField(grsaisettlement.FieldLastErrorSummary, field.TypeString, value)
	}
	if _u.mutation.LastErrorSummaryCleared() {
		_spec.ClearField(grsaisettlement.FieldLastErrorSummary, field.TypeString)
	}
	if value, ok := _u.mutation.SettledAmount(); ok {
		_spec.SetField(grsaisettlement.FieldSettledAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSettledAmount(); ok {
		_spec.AddField(grsaisettlement.FieldSettledAmount, field.TypeFloat64, value)
	}
	if _u.mutation.SettledAmountCleared() {
		_spec.ClearField(grsaisettlement.FieldSettledAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(grsaisettlement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpstreamBoundAt(); ok {
		_spec.SetField(grsaisettlement.FieldUpstreamBoundAt, field.TypeTime, value)
	}
	if _u.mutation.UpstreamBoundAtCleared() {
		_spec.ClearField(grsaisettlement.FieldUpstreamBoundAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ResultUpdatedAt(); ok {
		_spec.SetField(grsaisettlement.FieldResultUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ResultUpdatedAtCleared() {
		_spec.ClearField(grsaisettlement.FieldResultUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(grsaisettlement.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(grsaisettlement.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClosedAt(); ok {
		_spec.SetField(grsaisettlement.FieldClosedAt, field.TypeTime, value)
	}
	if _u.mutation.ClosedAtCleared() {
		_spec.ClearField(grsaisettlement.FieldClosedAt, field.TypeTime)
	}
	_node = &GrsaiSettlement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{grsaisettlement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
