// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/grsaitaskpayload"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GrsaiTaskPayloadDelete is the builder for deleting a GrsaiTaskPayload entity.
type GrsaiTaskPayloadDelete struct {
	config
	hooks    []Hook
	mutation *GrsaiTaskPayloadMutation
}

// Where appends a list predicates to the GrsaiTaskPayloadDelete builder.
func (_d *GrsaiTaskPayloadDelete) Where(ps ...predicate.GrsaiTaskPayload) *GrsaiTaskPayloadDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GrsaiTaskPayloadDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GrsaiTaskPayloadDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GrsaiTaskPayloadDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grsaitaskpayload.Table, sqlgraph.NewFieldSpec(grsaitaskpayload.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GrsaiTaskPayloadDeleteOne is the builder for deleting a single GrsaiTaskPayload entity.
type GrsaiTaskPayloadDeleteOne struct {
	_d *GrsaiTaskPayloadDelete
}

// Where appends a list predicates to the GrsaiTaskPayloadDelete builder.
func (_d *GrsaiTaskPayloadDeleteOne) Where(ps ...predicate.GrsaiTaskPayload) *GrsaiTaskPayloadDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GrsaiTaskPayloadDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grsaitaskpayload.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GrsaiTaskPayloadDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
