// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/grsaisettlement"
	"github.com/Wei-Shaw/sub2api/ent/grsaitaskpayload"
)

// GrsaiTaskPayload is the model entity for the GrsaiTaskPayload schema.
type GrsaiTaskPayload struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Ciphertext holds the value of the "ciphertext" field.
	Ciphertext string `json:"ciphertext,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GrsaiTaskPayloadQuery when eager-loading is set.
	Edges         GrsaiTaskPayloadEdges `json:"edges"`
	settlement_id *int64
	selectValues  sql.SelectValues
}

// GrsaiTaskPayloadEdges holds the relations/edges for other nodes in the graph.
type GrsaiTaskPayloadEdges struct {
	// Settlement holds the value of the settlement edge.
	Settlement *GrsaiSettlement `json:"settlement,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SettlementOrErr returns the Settlement value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GrsaiTaskPayloadEdges) SettlementOrErr() (*GrsaiSettlement, error) {
	if e.Settlement != nil {
		return e.Settlement, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: grsaisettlement.Label}
	}
	return nil, &NotLoadedError{edge: "settlement"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GrsaiTaskPayload) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grsaitaskpayload.FieldID:
			values[i] = new(sql.NullInt64)
		case grsaitaskpayload.FieldCiphertext:
			values[i] = new(sql.NullString)
		case grsaitaskpayload.FieldExpiresAt, grsaitaskpayload.FieldCreatedAt, grsaitaskpayload.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case grsaitaskpayload.ForeignKeys[0]: // settlement_id
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GrsaiTaskPayload fields.
func (_m *GrsaiTaskPayload) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grsaitaskpayload.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case grsaitaskpayload.FieldCiphertext:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ciphertext", values[i])
			} else if value.Valid {
				_m.Ciphertext = value.String
			}
		case grsaitaskpayload.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case grsaitaskpayload.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case grsaitaskpayload.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case grsaitaskpayload.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field settlement_id", value)
			} else if value.Valid {
				_m.settlement_id = new(int64)
				*_m.settlement_id = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GrsaiTaskPayload.
// This includes values selected through modifiers, order, etc.
func (_m *GrsaiTaskPayload) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySettlement queries the "settlement" edge of the GrsaiTaskPayload entity.
func (_m *GrsaiTaskPayload) QuerySettlement() *GrsaiSettlementQuery {
	return NewGrsaiTaskPayloadClient(_m.config).QuerySettlement(_m)
}

// Update returns a builder for updating this GrsaiTaskPayload.
// Note that you need to call GrsaiTaskPayload.Unwrap() before calling this method if this GrsaiTaskPayload
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GrsaiTaskPayload) Update() *GrsaiTaskPayloadUpdateOne {
	return NewGrsaiTaskPayloadClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GrsaiTaskPayload entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GrsaiTaskPayload) Unwrap() *GrsaiTaskPayload {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GrsaiTaskPayload is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GrsaiTaskPayload) String() string {
	var builder strings.Builder
	builder.WriteString("GrsaiTaskPayload(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ciphertext=")
	builder.WriteString(_m.Ciphertext)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GrsaiTaskPayloads is a parsable slice of GrsaiTaskPayload.
type GrsaiTaskPayloads []*GrsaiTaskPayload
