// Code generated by ent, DO NOT EDIT.

package grsaisettlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the grsaisettlement type in the database.
	Label = "grsai_settlement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldBaseUnitPrice holds the string denoting the base_unit_price field in the database.
	FieldBaseUnitPrice = "base_unit_price"
	// FieldGroupRateMultiplier holds the string denoting the group_rate_multiplier field in the database.
	FieldGroupRateMultiplier = "group_rate_multiplier"
	// FieldAccountRateMultiplier holds the string denoting the account_rate_multiplier field in the database.
	FieldAccountRateMultiplier = "account_rate_multiplier"
	// FieldBillableUnitPrice holds the string denoting the billable_unit_price field in the database.
	FieldBillableUnitPrice = "billable_unit_price"
	// FieldRequestedImageCount holds the string denoting the requested_image_count field in the database.
	FieldRequestedImageCount = "requested_image_count"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldBillingIdempotencyKey holds the string denoting the billing_idempotency_key field in the database.
	FieldBillingIdempotencyKey = "billing_idempotency_key"
	// FieldPublicTaskID holds the string denoting the public_task_id field in the database.
	FieldPublicTaskID = "public_task_id"
	// FieldDeliveryMode holds the string denoting the delivery_mode field in the database.
	FieldDeliveryMode = "delivery_mode"
	// FieldAsyncStartedAt holds the string denoting the async_started_at field in the database.
	FieldAsyncStartedAt = "async_started_at"
	// FieldProgress holds the string denoting the progress field in the database.
	FieldProgress = "progress"
	// FieldResultUrls holds the string denoting the result_urls field in the database.
	FieldResultUrls = "result_urls"
	// FieldHoldAmount holds the string denoting the hold_amount field in the database.
	FieldHoldAmount = "hold_amount"
	// FieldHoldState holds the string denoting the hold_state field in the database.
	FieldHoldState = "hold_state"
	// FieldPayloadDeleteAfter holds the string denoting the payload_delete_after field in the database.
	FieldPayloadDeleteAfter = "payload_delete_after"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldUpstreamTaskID holds the string denoting the upstream_task_id field in the database.
	FieldUpstreamTaskID = "upstream_task_id"
	// FieldUpstreamStatus holds the string denoting the upstream_status field in the database.
	FieldUpstreamStatus = "upstream_status"
	// FieldInternalStatus holds the string denoting the internal_status field in the database.
	FieldInternalStatus = "internal_status"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldSettlementRetryCount holds the string denoting the settlement_retry_count field in the database.
	FieldSettlementRetryCount = "settlement_retry_count"
	// FieldClaimVersion holds the string denoting the claim_version field in the database.
	FieldClaimVersion = "claim_version"
	// FieldNextAttemptAt holds the string denoting the next_attempt_at field in the database.
	FieldNextAttemptAt = "next_attempt_at"
	// FieldLastErrorSummary holds the string denoting the last_error_summary field in the database.
	FieldLastErrorSummary = "last_error_summary"
	// FieldSettledAmount holds the string denoting the settled_amount field in the database.
	FieldSettledAmount = "settled_amount"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUpstreamBoundAt holds the string denoting the upstream_bound_at field in the database.
	FieldUpstreamBoundAt = "upstream_bound_at"
	// FieldResultUpdatedAt holds the string denoting the result_updated_at field in the database.
	FieldResultUpdatedAt = "result_updated_at"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldClosedAt holds the string denoting the closed_at field in the database.
	FieldClosedAt = "closed_at"
	// EdgeTaskPayload holds the string denoting the task_payload edge name in mutations.
	EdgeTaskPayload = "task_payload"
	// GrsaiTaskPayloadFieldID holds the string denoting the ID field of the GrsaiTaskPayload.
	GrsaiTaskPayloadFieldID = "settlement_id"
	// Table holds the table name of the grsaisettlement in the database.
	Table = "grsai_settlements"
	// TaskPayloadTable is the table that holds the task_payload relation/edge.
	TaskPayloadTable = "grsai_task_payloads"
	// TaskPayloadInverseTable is the table name for the GrsaiTaskPayload entity.
	// It exists in this package in order to avoid circular dependency with the "grsaitaskpayload" package.
	TaskPayloadInverseTable = "grsai_task_payloads"
	// TaskPayloadColumn is the table column denoting the task_payload relation/edge.
	TaskPayloadColumn = "settlement_id"
)

// Columns holds all SQL columns for grsaisettlement fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldGroupID,
	FieldUserID,
	FieldAPIKeyID,
	FieldModel,
	FieldBaseUnitPrice,
	FieldGroupRateMultiplier,
	FieldAccountRateMultiplier,
	FieldBillableUnitPrice,
	FieldRequestedImageCount,
	FieldCurrency,
	FieldBillingIdempotencyKey,
	FieldPublicTaskID,
	FieldDeliveryMode,
	FieldAsyncStartedAt,
	FieldProgress,
	FieldResultUrls,
	FieldHoldAmount,
	FieldHoldState,
	FieldPayloadDeleteAfter,
	FieldExpiresAt,
	FieldUpstreamTaskID,
	FieldUpstreamStatus,
	FieldInternalStatus,
	FieldRetryCount,
	FieldSettlementRetryCount,
	FieldClaimVersion,
	FieldNextAttemptAt,
	FieldLastErrorSummary,
	FieldSettledAmount,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUpstreamBoundAt,
	FieldResultUpdatedAt,
	FieldSettledAt,
	FieldClosedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	CurrencyValidator func(string) error
	// BillingIdempotencyKeyValidator is a validator for the "billing_idempotency_key" field. It is called by the builders before save.
	BillingIdempotencyKeyValidator func(string) error
	// PublicTaskIDValidator is a validator for the "public_task_id" field. It is called by the builders before save.
	PublicTaskIDValidator func(string) error
	// DefaultDeliveryMode holds the default value on creation for the "delivery_mode" field.
	DefaultDeliveryMode string
	// DeliveryModeValidator is a validator for the "delivery_mode" field. It is called by the builders before save.
	DeliveryModeValidator func(string) error
	// DefaultProgress holds the default value on creation for the "progress" field.
	DefaultProgress int
	// ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	ProgressValidator func(int) error
	// DefaultResultUrls holds the default value on creation for the "result_urls" field.
	DefaultResultUrls []string
	// DefaultHoldAmount holds the default value on creation for the "hold_amount" field.
	DefaultHoldAmount float64
	// DefaultHoldState holds the default value on creation for the "hold_state" field.
	DefaultHoldState string
	// HoldStateValidator is a validator for the "hold_state" field. It is called by the builders before save.
	HoldStateValidator func(string) error
	// UpstreamTaskIDValidator is a validator for the "upstream_task_id" field. It is called by the builders before save.
	UpstreamTaskIDValidator func(string) error
	// DefaultUpstreamStatus holds the default value on creation for the "upstream_status" field.
	DefaultUpstreamStatus string
	// UpstreamStatusValidator is a validator for the "upstream_status" field. It is called by the builders before save.
	UpstreamStatusValidator func(string) error
	// DefaultInternalStatus holds the default value on creation for the "internal_status" field.
	DefaultInternalStatus string
	// InternalStatusValidator is a validator for the "internal_status" field. It is called by the builders before save.
	InternalStatusValidator func(string) error
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultSettlementRetryCount holds the default value on creation for the "settlement_retry_count" field.
	DefaultSettlementRetryCount int
	// DefaultClaimVersion holds the default value on creation for the "claim_version" field.
	DefaultClaimVersion int64
	// LastErrorSummaryValidator is a validator for the "last_error_summary" field. It is called by the builders before save.
	LastErrorSummaryValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GrsaiSettlement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByBaseUnitPrice orders the results by the base_unit_price field.
func ByBaseUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseUnitPrice, opts...).ToFunc()
}

// ByGroupRateMultiplier orders the results by the group_rate_multiplier field.
func ByGroupRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupRateMultiplier, opts...).ToFunc()
}

// ByAccountRateMultiplier orders the results by the account_rate_multiplier field.
func ByAccountRateMultiplier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountRateMultiplier, opts...).ToFunc()
}

// ByBillableUnitPrice orders the results by the billable_unit_price field.
func ByBillableUnitPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillableUnitPrice, opts...).ToFunc()
}

// ByRequestedImageCount orders the results by the requested_image_count field.
func ByRequestedImageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedImageCount, opts...).ToFunc()
}

// ByCurrency orders the results by the currency field.
func ByCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrency, opts...).ToFunc()
}

// ByBillingIdempotencyKey orders the results by the billing_idempotency_key field.
func ByBillingIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBillingIdempotencyKey, opts...).ToFunc()
}

// ByPublicTaskID orders the results by the public_task_id field.
func ByPublicTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicTaskID, opts...).ToFunc()
}

// ByDeliveryMode orders the results by the delivery_mode field.
func ByDeliveryMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryMode, opts...).ToFunc()
}

// ByAsyncStartedAt orders the results by the async_started_at field.
func ByAsyncStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAsyncStartedAt, opts...).ToFunc()
}

// ByProgress orders the results by the progress field.
func ByProgress(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProgress, opts...).ToFunc()
}

// ByHoldAmount orders the results by the hold_amount field.
func ByHoldAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoldAmount, opts...).ToFunc()
}

// ByHoldState orders the results by the hold_state field.
func ByHoldState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoldState, opts...).ToFunc()
}

// ByPayloadDeleteAfter orders the results by the payload_delete_after field.
func ByPayloadDeleteAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadDeleteAfter, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByUpstreamTaskID orders the results by the upstream_task_id field.
func ByUpstreamTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamTaskID, opts...).ToFunc()
}

// ByUpstreamStatus orders the results by the upstream_status field.
func ByUpstreamStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamStatus, opts...).ToFunc()
}

// ByInternalStatus orders the results by the internal_status field.
func ByInternalStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInternalStatus, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// BySettlementRetryCount orders the results by the settlement_retry_count field.
func BySettlementRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettlementRetryCount, opts...).ToFunc()
}

// ByClaimVersion orders the results by the claim_version field.
func ByClaimVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClaimVersion, opts...).ToFunc()
}

// ByNextAttemptAt orders the results by the next_attempt_at field.
func ByNextAttemptAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextAttemptAt, opts...).ToFunc()
}

// ByLastErrorSummary orders the results by the last_error_summary field.
func ByLastErrorSummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastErrorSummary, opts...).ToFunc()
}

// BySettledAmount orders the results by the settled_amount field.
func BySettledAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAmount, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUpstreamBoundAt orders the results by the upstream_bound_at field.
func ByUpstreamBoundAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamBoundAt, opts...).ToFunc()
}

// ByResultUpdatedAt orders the results by the result_updated_at field.
func ByResultUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResultUpdatedAt, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// ByClosedAt orders the results by the closed_at field.
func ByClosedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClosedAt, opts...).ToFunc()
}

// ByTaskPayloadField orders the results by task_payload field.
func ByTaskPayloadField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskPayloadStep(), sql.OrderByField(field, opts...))
	}
}
func newTaskPayloadStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskPayloadInverseTable, GrsaiTaskPayloadFieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, TaskPayloadTable, TaskPayloadColumn),
	)
}
