// Code generated by ent, DO NOT EDIT.

package grsaisettlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldGroupID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldAPIKeyID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldModel, v))
}

// BaseUnitPrice applies equality check predicate on the "base_unit_price" field. It's identical to BaseUnitPriceEQ.
func BaseUnitPrice(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldBaseUnitPrice, v))
}

// GroupRateMultiplier applies equality check predicate on the "group_rate_multiplier" field. It's identical to GroupRateMultiplierEQ.
func GroupRateMultiplier(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldGroupRateMultiplier, v))
}

// AccountRateMultiplier applies equality check predicate on the "account_rate_multiplier" field. It's identical to AccountRateMultiplierEQ.
func AccountRateMultiplier(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldAccountRateMultiplier, v))
}

// BillableUnitPrice applies equality check predicate on the "billable_unit_price" field. It's identical to BillableUnitPriceEQ.
func BillableUnitPrice(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldBillableUnitPrice, v))
}

// RequestedImageCount applies equality check predicate on the "requested_image_count" field. It's identical to RequestedImageCountEQ.
func RequestedImageCount(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldRequestedImageCount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldCurrency, v))
}

// BillingIdempotencyKey applies equality check predicate on the "billing_idempotency_key" field. It's identical to BillingIdempotencyKeyEQ.
func BillingIdempotencyKey(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldBillingIdempotencyKey, v))
}

// PublicTaskID applies equality check predicate on the "public_task_id" field. It's identical to PublicTaskIDEQ.
func PublicTaskID(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldPublicTaskID, v))
}

// DeliveryMode applies equality check predicate on the "delivery_mode" field. It's identical to DeliveryModeEQ.
func DeliveryMode(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldDeliveryMode, v))
}

// Progress applies equality check predicate on the "progress" field. It's identical to ProgressEQ.
func Progress(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldProgress, v))
}

// HoldAmount applies equality check predicate on the "hold_amount" field. It's identical to HoldAmountEQ.
func HoldAmount(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldHoldAmount, v))
}

// HoldState applies equality check predicate on the "hold_state" field. It's identical to HoldStateEQ.
func HoldState(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldHoldState, v))
}

// PayloadDeleteAfter applies equality check predicate on the "payload_delete_after" field. It's identical to PayloadDeleteAfterEQ.
func PayloadDeleteAfter(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldPayloadDeleteAfter, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldExpiresAt, v))
}

// UpstreamTaskID applies equality check predicate on the "upstream_task_id" field. It's identical to UpstreamTaskIDEQ.
func UpstreamTaskID(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamStatus applies equality check predicate on the "upstream_status" field. It's identical to UpstreamStatusEQ.
func UpstreamStatus(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUpstreamStatus, v))
}

// InternalStatus applies equality check predicate on the "internal_status" field. It's identical to InternalStatusEQ.
func InternalStatus(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldInternalStatus, v))
}

// RetryCount applies equality check predicate on the "retry_count" field. It's identical to RetryCountEQ.
func RetryCount(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldRetryCount, v))
}

// SettlementRetryCount applies equality check predicate on the "settlement_retry_count" field. It's identical to SettlementRetryCountEQ.
func SettlementRetryCount(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldSettlementRetryCount, v))
}

// ClaimVersion applies equality check predicate on the "claim_version" field. It's identical to ClaimVersionEQ.
func ClaimVersion(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldClaimVersion, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldNextAttemptAt, v))
}

// LastErrorSummary applies equality check predicate on the "last_error_summary" field. It's identical to LastErrorSummaryEQ.
func LastErrorSummary(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldLastErrorSummary, v))
}

// SettledAmount applies equality check predicate on the "settled_amount" field. It's identical to SettledAmountEQ.
func SettledAmount(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldSettledAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpstreamBoundAt applies equality check predicate on the "upstream_bound_at" field. It's identical to UpstreamBoundAtEQ.
func UpstreamBoundAt(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUpstreamBoundAt, v))
}

// ResultUpdatedAt applies equality check predicate on the "result_updated_at" field. It's identical to ResultUpdatedAtEQ.
func ResultUpdatedAt(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldResultUpdatedAt, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldSettledAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldClosedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldAccountID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldGroupID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldAPIKeyID, v))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldModel, v))
}

// BaseUnitPriceEQ applies the EQ predicate on the "base_unit_price" field.
func BaseUnitPriceEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldBaseUnitPrice, v))
}

// BaseUnitPriceNEQ applies the NEQ predicate on the "base_unit_price" field.
func BaseUnitPriceNEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldBaseUnitPrice, v))
}

// BaseUnitPriceIn applies the In predicate on the "base_unit_price" field.
func BaseUnitPriceIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldBaseUnitPrice, vs...))
}

// BaseUnitPriceNotIn applies the NotIn predicate on the "base_unit_price" field.
func BaseUnitPriceNotIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldBaseUnitPrice, vs...))
}

// BaseUnitPriceGT applies the GT predicate on the "base_unit_price" field.
func BaseUnitPriceGT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldBaseUnitPrice, v))
}

// BaseUnitPriceGTE applies the GTE predicate on the "base_unit_price" field.
func BaseUnitPriceGTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldBaseUnitPrice, v))
}

// BaseUnitPriceLT applies the LT predicate on the "base_unit_price" field.
func BaseUnitPriceLT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldBaseUnitPrice, v))
}

// BaseUnitPriceLTE applies the LTE predicate on the "base_unit_price" field.
func BaseUnitPriceLTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldBaseUnitPrice, v))
}

// GroupRateMultiplierEQ applies the EQ predicate on the "group_rate_multiplier" field.
func GroupRateMultiplierEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldGroupRateMultiplier, v))
}

// GroupRateMultiplierNEQ applies the NEQ predicate on the "group_rate_multiplier" field.
func GroupRateMultiplierNEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldGroupRateMultiplier, v))
}

// GroupRateMultiplierIn applies the In predicate on the "group_rate_multiplier" field.
func GroupRateMultiplierIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldGroupRateMultiplier, vs...))
}

// GroupRateMultiplierNotIn applies the NotIn predicate on the "group_rate_multiplier" field.
func GroupRateMultiplierNotIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldGroupRateMultiplier, vs...))
}

// GroupRateMultiplierGT applies the GT predicate on the "group_rate_multiplier" field.
func GroupRateMultiplierGT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldGroupRateMultiplier, v))
}

// GroupRateMultiplierGTE applies the GTE predicate on the "group_rate_multiplier" field.
func GroupRateMultiplierGTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldGroupRateMultiplier, v))
}

// GroupRateMultiplierLT applies the LT predicate on the "group_rate_multiplier" field.
func GroupRateMultiplierLT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldGroupRateMultiplier, v))
}

// GroupRateMultiplierLTE applies the LTE predicate on the "group_rate_multiplier" field.
func GroupRateMultiplierLTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldGroupRateMultiplier, v))
}

// AccountRateMultiplierEQ applies the EQ predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierNEQ applies the NEQ predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierNEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierIn applies the In predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldAccountRateMultiplier, vs...))
}

// AccountRateMultiplierNotIn applies the NotIn predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierNotIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldAccountRateMultiplier, vs...))
}

// AccountRateMultiplierGT applies the GT predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierGT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierGTE applies the GTE predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierGTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierLT applies the LT predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierLT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldAccountRateMultiplier, v))
}

// AccountRateMultiplierLTE applies the LTE predicate on the "account_rate_multiplier" field.
func AccountRateMultiplierLTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldAccountRateMultiplier, v))
}

// BillableUnitPriceEQ applies the EQ predicate on the "billable_unit_price" field.
func BillableUnitPriceEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldBillableUnitPrice, v))
}

// BillableUnitPriceNEQ applies the NEQ predicate on the "billable_unit_price" field.
func BillableUnitPriceNEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldBillableUnitPrice, v))
}

// BillableUnitPriceIn applies the In predicate on the "billable_unit_price" field.
func BillableUnitPriceIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldBillableUnitPrice, vs...))
}

// BillableUnitPriceNotIn applies the NotIn predicate on the "billable_unit_price" field.
func BillableUnitPriceNotIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldBillableUnitPrice, vs...))
}

// BillableUnitPriceGT applies the GT predicate on the "billable_unit_price" field.
func BillableUnitPriceGT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldBillableUnitPrice, v))
}

// BillableUnitPriceGTE applies the GTE predicate on the "billable_unit_price" field.
func BillableUnitPriceGTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldBillableUnitPrice, v))
}

// BillableUnitPriceLT applies the LT predicate on the "billable_unit_price" field.
func BillableUnitPriceLT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldBillableUnitPrice, v))
}

// BillableUnitPriceLTE applies the LTE predicate on the "billable_unit_price" field.
func BillableUnitPriceLTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldBillableUnitPrice, v))
}

// RequestedImageCountEQ applies the EQ predicate on the "requested_image_count" field.
func RequestedImageCountEQ(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldRequestedImageCount, v))
}

// RequestedImageCountNEQ applies the NEQ predicate on the "requested_image_count" field.
func RequestedImageCountNEQ(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldRequestedImageCount, v))
}

// RequestedImageCountIn applies the In predicate on the "requested_image_count" field.
func RequestedImageCountIn(vs ...int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldRequestedImageCount, vs...))
}

// RequestedImageCountNotIn applies the NotIn predicate on the "requested_image_count" field.
func RequestedImageCountNotIn(vs ...int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldRequestedImageCount, vs...))
}

// RequestedImageCountGT applies the GT predicate on the "requested_image_count" field.
func RequestedImageCountGT(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldRequestedImageCount, v))
}

// RequestedImageCountGTE applies the GTE predicate on the "requested_image_count" field.
func RequestedImageCountGTE(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldRequestedImageCount, v))
}

// RequestedImageCountLT applies the LT predicate on the "requested_image_count" field.
func RequestedImageCountLT(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldRequestedImageCount, v))
}

// RequestedImageCountLTE applies the LTE predicate on the "requested_image_count" field.
func RequestedImageCountLTE(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldRequestedImageCount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldCurrency, v))
}

// BillingIdempotencyKeyEQ applies the EQ predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyNEQ applies the NEQ predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyIn applies the In predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldBillingIdempotencyKey, vs...))
}

// BillingIdempotencyKeyNotIn applies the NotIn predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldBillingIdempotencyKey, vs...))
}

// BillingIdempotencyKeyGT applies the GT predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyGTE applies the GTE predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyLT applies the LT predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyLTE applies the LTE predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyContains applies the Contains predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyHasPrefix applies the HasPrefix predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyHasSuffix applies the HasSuffix predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyEqualFold applies the EqualFold predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldBillingIdempotencyKey, v))
}

// BillingIdempotencyKeyContainsFold applies the ContainsFold predicate on the "billing_idempotency_key" field.
func BillingIdempotencyKeyContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldBillingIdempotencyKey, v))
}

// PublicTaskIDEQ applies the EQ predicate on the "public_task_id" field.
func PublicTaskIDEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldPublicTaskID, v))
}

// PublicTaskIDNEQ applies the NEQ predicate on the "public_task_id" field.
func PublicTaskIDNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldPublicTaskID, v))
}

// PublicTaskIDIn applies the In predicate on the "public_task_id" field.
func PublicTaskIDIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldPublicTaskID, vs...))
}

// PublicTaskIDNotIn applies the NotIn predicate on the "public_task_id" field.
func PublicTaskIDNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldPublicTaskID, vs...))
}

// PublicTaskIDGT applies the GT predicate on the "public_task_id" field.
func PublicTaskIDGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldPublicTaskID, v))
}

// PublicTaskIDGTE applies the GTE predicate on the "public_task_id" field.
func PublicTaskIDGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldPublicTaskID, v))
}

// PublicTaskIDLT applies the LT predicate on the "public_task_id" field.
func PublicTaskIDLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldPublicTaskID, v))
}

// PublicTaskIDLTE applies the LTE predicate on the "public_task_id" field.
func PublicTaskIDLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldPublicTaskID, v))
}

// PublicTaskIDContains applies the Contains predicate on the "public_task_id" field.
func PublicTaskIDContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldPublicTaskID, v))
}

// PublicTaskIDHasPrefix applies the HasPrefix predicate on the "public_task_id" field.
func PublicTaskIDHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldPublicTaskID, v))
}

// PublicTaskIDHasSuffix applies the HasSuffix predicate on the "public_task_id" field.
func PublicTaskIDHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldPublicTaskID, v))
}

// PublicTaskIDIsNil applies the IsNil predicate on the "public_task_id" field.
func PublicTaskIDIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldPublicTaskID))
}

// PublicTaskIDNotNil applies the NotNil predicate on the "public_task_id" field.
func PublicTaskIDNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldPublicTaskID))
}

// PublicTaskIDEqualFold applies the EqualFold predicate on the "public_task_id" field.
func PublicTaskIDEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldPublicTaskID, v))
}

// PublicTaskIDContainsFold applies the ContainsFold predicate on the "public_task_id" field.
func PublicTaskIDContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldPublicTaskID, v))
}

// DeliveryModeEQ applies the EQ predicate on the "delivery_mode" field.
func DeliveryModeEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldDeliveryMode, v))
}

// DeliveryModeNEQ applies the NEQ predicate on the "delivery_mode" field.
func DeliveryModeNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldDeliveryMode, v))
}

// DeliveryModeIn applies the In predicate on the "delivery_mode" field.
func DeliveryModeIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldDeliveryMode, vs...))
}

// DeliveryModeNotIn applies the NotIn predicate on the "delivery_mode" field.
func DeliveryModeNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldDeliveryMode, vs...))
}

// DeliveryModeGT applies the GT predicate on the "delivery_mode" field.
func DeliveryModeGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldDeliveryMode, v))
}

// DeliveryModeGTE applies the GTE predicate on the "delivery_mode" field.
func DeliveryModeGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldDeliveryMode, v))
}

// DeliveryModeLT applies the LT predicate on the "delivery_mode" field.
func DeliveryModeLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldDeliveryMode, v))
}

// DeliveryModeLTE applies the LTE predicate on the "delivery_mode" field.
func DeliveryModeLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldDeliveryMode, v))
}

// DeliveryModeContains applies the Contains predicate on the "delivery_mode" field.
func DeliveryModeContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldDeliveryMode, v))
}

// DeliveryModeHasPrefix applies the HasPrefix predicate on the "delivery_mode" field.
func DeliveryModeHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldDeliveryMode, v))
}

// DeliveryModeHasSuffix applies the HasSuffix predicate on the "delivery_mode" field.
func DeliveryModeHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldDeliveryMode, v))
}

// DeliveryModeEqualFold applies the EqualFold predicate on the "delivery_mode" field.
func DeliveryModeEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldDeliveryMode, v))
}

// DeliveryModeContainsFold applies the ContainsFold predicate on the "delivery_mode" field.
func DeliveryModeContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldDeliveryMode, v))
}

// ProgressEQ applies the EQ predicate on the "progress" field.
func ProgressEQ(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldProgress, v))
}

// ProgressNEQ applies the NEQ predicate on the "progress" field.
func ProgressNEQ(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldProgress, v))
}

// ProgressIn applies the In predicate on the "progress" field.
func ProgressIn(vs ...int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldProgress, vs...))
}

// ProgressNotIn applies the NotIn predicate on the "progress" field.
func ProgressNotIn(vs ...int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldProgress, vs...))
}

// ProgressGT applies the GT predicate on the "progress" field.
func ProgressGT(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldProgress, v))
}

// ProgressGTE applies the GTE predicate on the "progress" field.
func ProgressGTE(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldProgress, v))
}

// ProgressLT applies the LT predicate on the "progress" field.
func ProgressLT(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldProgress, v))
}

// ProgressLTE applies the LTE predicate on the "progress" field.
func ProgressLTE(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldProgress, v))
}

// HoldAmountEQ applies the EQ predicate on the "hold_amount" field.
func HoldAmountEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldHoldAmount, v))
}

// HoldAmountNEQ applies the NEQ predicate on the "hold_amount" field.
func HoldAmountNEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldHoldAmount, v))
}

// HoldAmountIn applies the In predicate on the "hold_amount" field.
func HoldAmountIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldHoldAmount, vs...))
}

// HoldAmountNotIn applies the NotIn predicate on the "hold_amount" field.
func HoldAmountNotIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldHoldAmount, vs...))
}

// HoldAmountGT applies the GT predicate on the "hold_amount" field.
func HoldAmountGT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldHoldAmount, v))
}

// HoldAmountGTE applies the GTE predicate on the "hold_amount" field.
func HoldAmountGTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldHoldAmount, v))
}

// HoldAmountLT applies the LT predicate on the "hold_amount" field.
func HoldAmountLT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldHoldAmount, v))
}

// HoldAmountLTE applies the LTE predicate on the "hold_amount" field.
func HoldAmountLTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldHoldAmount, v))
}

// HoldStateEQ applies the EQ predicate on the "hold_state" field.
func HoldStateEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldHoldState, v))
}

// HoldStateNEQ applies the NEQ predicate on the "hold_state" field.
func HoldStateNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldHoldState, v))
}

// HoldStateIn applies the In predicate on the "hold_state" field.
func HoldStateIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldHoldState, vs...))
}

// HoldStateNotIn applies the NotIn predicate on the "hold_state" field.
func HoldStateNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldHoldState, vs...))
}

// HoldStateGT applies the GT predicate on the "hold_state" field.
func HoldStateGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldHoldState, v))
}

// HoldStateGTE applies the GTE predicate on the "hold_state" field.
func HoldStateGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldHoldState, v))
}

// HoldStateLT applies the LT predicate on the "hold_state" field.
func HoldStateLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldHoldState, v))
}

// HoldStateLTE applies the LTE predicate on the "hold_state" field.
func HoldStateLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldHoldState, v))
}

// HoldStateContains applies the Contains predicate on the "hold_state" field.
func HoldStateContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldHoldState, v))
}

// HoldStateHasPrefix applies the HasPrefix predicate on the "hold_state" field.
func HoldStateHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldHoldState, v))
}

// HoldStateHasSuffix applies the HasSuffix predicate on the "hold_state" field.
func HoldStateHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldHoldState, v))
}

// HoldStateEqualFold applies the EqualFold predicate on the "hold_state" field.
func HoldStateEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldHoldState, v))
}

// HoldStateContainsFold applies the ContainsFold predicate on the "hold_state" field.
func HoldStateContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldHoldState, v))
}

// PayloadDeleteAfterEQ applies the EQ predicate on the "payload_delete_after" field.
func PayloadDeleteAfterEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldPayloadDeleteAfter, v))
}

// PayloadDeleteAfterNEQ applies the NEQ predicate on the "payload_delete_after" field.
func PayloadDeleteAfterNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldPayloadDeleteAfter, v))
}

// PayloadDeleteAfterIn applies the In predicate on the "payload_delete_after" field.
func PayloadDeleteAfterIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldPayloadDeleteAfter, vs...))
}

// PayloadDeleteAfterNotIn applies the NotIn predicate on the "payload_delete_after" field.
func PayloadDeleteAfterNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldPayloadDeleteAfter, vs...))
}

// PayloadDeleteAfterGT applies the GT predicate on the "payload_delete_after" field.
func PayloadDeleteAfterGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldPayloadDeleteAfter, v))
}

// PayloadDeleteAfterGTE applies the GTE predicate on the "payload_delete_after" field.
func PayloadDeleteAfterGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldPayloadDeleteAfter, v))
}

// PayloadDeleteAfterLT applies the LT predicate on the "payload_delete_after" field.
func PayloadDeleteAfterLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldPayloadDeleteAfter, v))
}

// PayloadDeleteAfterLTE applies the LTE predicate on the "payload_delete_after" field.
func PayloadDeleteAfterLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldPayloadDeleteAfter, v))
}

// PayloadDeleteAfterIsNil applies the IsNil predicate on the "payload_delete_after" field.
func PayloadDeleteAfterIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldPayloadDeleteAfter))
}

// PayloadDeleteAfterNotNil applies the NotNil predicate on the "payload_delete_after" field.
func PayloadDeleteAfterNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldPayloadDeleteAfter))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldExpiresAt))
}

// UpstreamTaskIDEQ applies the EQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDNEQ applies the NEQ predicate on the "upstream_task_id" field.
func UpstreamTaskIDNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIn applies the In predicate on the "upstream_task_id" field.
func UpstreamTaskIDIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDNotIn applies the NotIn predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldUpstreamTaskID, vs...))
}

// UpstreamTaskIDGT applies the GT predicate on the "upstream_task_id" field.
func UpstreamTaskIDGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDGTE applies the GTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLT applies the LT predicate on the "upstream_task_id" field.
func UpstreamTaskIDLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDLTE applies the LTE predicate on the "upstream_task_id" field.
func UpstreamTaskIDLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContains applies the Contains predicate on the "upstream_task_id" field.
func UpstreamTaskIDContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasPrefix applies the HasPrefix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDHasSuffix applies the HasSuffix predicate on the "upstream_task_id" field.
func UpstreamTaskIDHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDIsNil applies the IsNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDNotNil applies the NotNil predicate on the "upstream_task_id" field.
func UpstreamTaskIDNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldUpstreamTaskID))
}

// UpstreamTaskIDEqualFold applies the EqualFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldUpstreamTaskID, v))
}

// UpstreamTaskIDContainsFold applies the ContainsFold predicate on the "upstream_task_id" field.
func UpstreamTaskIDContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldUpstreamTaskID, v))
}

// UpstreamStatusEQ applies the EQ predicate on the "upstream_status" field.
func UpstreamStatusEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusNEQ applies the NEQ predicate on the "upstream_status" field.
func UpstreamStatusNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldUpstreamStatus, v))
}

// UpstreamStatusIn applies the In predicate on the "upstream_status" field.
func UpstreamStatusIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusNotIn applies the NotIn predicate on the "upstream_status" field.
func UpstreamStatusNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldUpstreamStatus, vs...))
}

// UpstreamStatusGT applies the GT predicate on the "upstream_status" field.
func UpstreamStatusGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldUpstreamStatus, v))
}

// UpstreamStatusGTE applies the GTE predicate on the "upstream_status" field.
func UpstreamStatusGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldUpstreamStatus, v))
}

// UpstreamStatusLT applies the LT predicate on the "upstream_status" field.
func UpstreamStatusLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldUpstreamStatus, v))
}

// UpstreamStatusLTE applies the LTE predicate on the "upstream_status" field.
func UpstreamStatusLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldUpstreamStatus, v))
}

// UpstreamStatusContains applies the Contains predicate on the "upstream_status" field.
func UpstreamStatusContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldUpstreamStatus, v))
}

// UpstreamStatusHasPrefix applies the HasPrefix predicate on the "upstream_status" field.
func UpstreamStatusHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldUpstreamStatus, v))
}

// UpstreamStatusHasSuffix applies the HasSuffix predicate on the "upstream_status" field.
func UpstreamStatusHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldUpstreamStatus, v))
}

// UpstreamStatusEqualFold applies the EqualFold predicate on the "upstream_status" field.
func UpstreamStatusEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldUpstreamStatus, v))
}

// UpstreamStatusContainsFold applies the ContainsFold predicate on the "upstream_status" field.
func UpstreamStatusContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldUpstreamStatus, v))
}

// InternalStatusEQ applies the EQ predicate on the "internal_status" field.
func InternalStatusEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldInternalStatus, v))
}

// InternalStatusNEQ applies the NEQ predicate on the "internal_status" field.
func InternalStatusNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldInternalStatus, v))
}

// InternalStatusIn applies the In predicate on the "internal_status" field.
func InternalStatusIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldInternalStatus, vs...))
}

// InternalStatusNotIn applies the NotIn predicate on the "internal_status" field.
func InternalStatusNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldInternalStatus, vs...))
}

// InternalStatusGT applies the GT predicate on the "internal_status" field.
func InternalStatusGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldInternalStatus, v))
}

// InternalStatusGTE applies the GTE predicate on the "internal_status" field.
func InternalStatusGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldInternalStatus, v))
}

// InternalStatusLT applies the LT predicate on the "internal_status" field.
func InternalStatusLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldInternalStatus, v))
}

// InternalStatusLTE applies the LTE predicate on the "internal_status" field.
func InternalStatusLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldInternalStatus, v))
}

// InternalStatusContains applies the Contains predicate on the "internal_status" field.
func InternalStatusContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldInternalStatus, v))
}

// InternalStatusHasPrefix applies the HasPrefix predicate on the "internal_status" field.
func InternalStatusHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldInternalStatus, v))
}

// InternalStatusHasSuffix applies the HasSuffix predicate on the "internal_status" field.
func InternalStatusHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldInternalStatus, v))
}

// InternalStatusEqualFold applies the EqualFold predicate on the "internal_status" field.
func InternalStatusEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldInternalStatus, v))
}

// InternalStatusContainsFold applies the ContainsFold predicate on the "internal_status" field.
func InternalStatusContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldInternalStatus, v))
}

// RetryCountEQ applies the EQ predicate on the "retry_count" field.
func RetryCountEQ(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldRetryCount, v))
}

// RetryCountNEQ applies the NEQ predicate on the "retry_count" field.
func RetryCountNEQ(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldRetryCount, v))
}

// RetryCountIn applies the In predicate on the "retry_count" field.
func RetryCountIn(vs ...int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldRetryCount, vs...))
}

// RetryCountNotIn applies the NotIn predicate on the "retry_count" field.
func RetryCountNotIn(vs ...int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldRetryCount, vs...))
}

// RetryCountGT applies the GT predicate on the "retry_count" field.
func RetryCountGT(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldRetryCount, v))
}

// RetryCountGTE applies the GTE predicate on the "retry_count" field.
func RetryCountGTE(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldRetryCount, v))
}

// RetryCountLT applies the LT predicate on the "retry_count" field.
func RetryCountLT(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldRetryCount, v))
}

// RetryCountLTE applies the LTE predicate on the "retry_count" field.
func RetryCountLTE(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldRetryCount, v))
}

// SettlementRetryCountEQ applies the EQ predicate on the "settlement_retry_count" field.
func SettlementRetryCountEQ(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldSettlementRetryCount, v))
}

// SettlementRetryCountNEQ applies the NEQ predicate on the "settlement_retry_count" field.
func SettlementRetryCountNEQ(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldSettlementRetryCount, v))
}

// SettlementRetryCountIn applies the In predicate on the "settlement_retry_count" field.
func SettlementRetryCountIn(vs ...int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldSettlementRetryCount, vs...))
}

// SettlementRetryCountNotIn applies the NotIn predicate on the "settlement_retry_count" field.
func SettlementRetryCountNotIn(vs ...int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldSettlementRetryCount, vs...))
}

// SettlementRetryCountGT applies the GT predicate on the "settlement_retry_count" field.
func SettlementRetryCountGT(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldSettlementRetryCount, v))
}

// SettlementRetryCountGTE applies the GTE predicate on the "settlement_retry_count" field.
func SettlementRetryCountGTE(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldSettlementRetryCount, v))
}

// SettlementRetryCountLT applies the LT predicate on the "settlement_retry_count" field.
func SettlementRetryCountLT(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldSettlementRetryCount, v))
}

// SettlementRetryCountLTE applies the LTE predicate on the "settlement_retry_count" field.
func SettlementRetryCountLTE(v int) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldSettlementRetryCount, v))
}

// ClaimVersionEQ applies the EQ predicate on the "claim_version" field.
func ClaimVersionEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldClaimVersion, v))
}

// ClaimVersionNEQ applies the NEQ predicate on the "claim_version" field.
func ClaimVersionNEQ(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldClaimVersion, v))
}

// ClaimVersionIn applies the In predicate on the "claim_version" field.
func ClaimVersionIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldClaimVersion, vs...))
}

// ClaimVersionNotIn applies the NotIn predicate on the "claim_version" field.
func ClaimVersionNotIn(vs ...int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldClaimVersion, vs...))
}

// ClaimVersionGT applies the GT predicate on the "claim_version" field.
func ClaimVersionGT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldClaimVersion, v))
}

// ClaimVersionGTE applies the GTE predicate on the "claim_version" field.
func ClaimVersionGTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldClaimVersion, v))
}

// ClaimVersionLT applies the LT predicate on the "claim_version" field.
func ClaimVersionLT(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldClaimVersion, v))
}

// ClaimVersionLTE applies the LTE predicate on the "claim_version" field.
func ClaimVersionLTE(v int64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldClaimVersion, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldNextAttemptAt, v))
}

// LastErrorSummaryEQ applies the EQ predicate on the "last_error_summary" field.
func LastErrorSummaryEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldLastErrorSummary, v))
}

// LastErrorSummaryNEQ applies the NEQ predicate on the "last_error_summary" field.
func LastErrorSummaryNEQ(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldLastErrorSummary, v))
}

// LastErrorSummaryIn applies the In predicate on the "last_error_summary" field.
func LastErrorSummaryIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldLastErrorSummary, vs...))
}

// LastErrorSummaryNotIn applies the NotIn predicate on the "last_error_summary" field.
func LastErrorSummaryNotIn(vs ...string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldLastErrorSummary, vs...))
}

// LastErrorSummaryGT applies the GT predicate on the "last_error_summary" field.
func LastErrorSummaryGT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldLastErrorSummary, v))
}

// LastErrorSummaryGTE applies the GTE predicate on the "last_error_summary" field.
func LastErrorSummaryGTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldLastErrorSummary, v))
}

// LastErrorSummaryLT applies the LT predicate on the "last_error_summary" field.
func LastErrorSummaryLT(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldLastErrorSummary, v))
}

// LastErrorSummaryLTE applies the LTE predicate on the "last_error_summary" field.
func LastErrorSummaryLTE(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldLastErrorSummary, v))
}

// LastErrorSummaryContains applies the Contains predicate on the "last_error_summary" field.
func LastErrorSummaryContains(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContains(FieldLastErrorSummary, v))
}

// LastErrorSummaryHasPrefix applies the HasPrefix predicate on the "last_error_summary" field.
func LastErrorSummaryHasPrefix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasPrefix(FieldLastErrorSummary, v))
}

// LastErrorSummaryHasSuffix applies the HasSuffix predicate on the "last_error_summary" field.
func LastErrorSummaryHasSuffix(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldHasSuffix(FieldLastErrorSummary, v))
}

// LastErrorSummaryIsNil applies the IsNil predicate on the "last_error_summary" field.
func LastErrorSummaryIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldLastErrorSummary))
}

// LastErrorSummaryNotNil applies the NotNil predicate on the "last_error_summary" field.
func LastErrorSummaryNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldLastErrorSummary))
}

// LastErrorSummaryEqualFold applies the EqualFold predicate on the "last_error_summary" field.
func LastErrorSummaryEqualFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEqualFold(FieldLastErrorSummary, v))
}

// LastErrorSummaryContainsFold applies the ContainsFold predicate on the "last_error_summary" field.
func LastErrorSummaryContainsFold(v string) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldContainsFold(FieldLastErrorSummary, v))
}

// SettledAmountEQ applies the EQ predicate on the "settled_amount" field.
func SettledAmountEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldSettledAmount, v))
}

// SettledAmountNEQ applies the NEQ predicate on the "settled_amount" field.
func SettledAmountNEQ(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldSettledAmount, v))
}

// SettledAmountIn applies the In predicate on the "settled_amount" field.
func SettledAmountIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldSettledAmount, vs...))
}

// SettledAmountNotIn applies the NotIn predicate on the "settled_amount" field.
func SettledAmountNotIn(vs ...float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldSettledAmount, vs...))
}

// SettledAmountGT applies the GT predicate on the "settled_amount" field.
func SettledAmountGT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldSettledAmount, v))
}

// SettledAmountGTE applies the GTE predicate on the "settled_amount" field.
func SettledAmountGTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldSettledAmount, v))
}

// SettledAmountLT applies the LT predicate on the "settled_amount" field.
func SettledAmountLT(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldSettledAmount, v))
}

// SettledAmountLTE applies the LTE predicate on the "settled_amount" field.
func SettledAmountLTE(v float64) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldSettledAmount, v))
}

// SettledAmountIsNil applies the IsNil predicate on the "settled_amount" field.
func SettledAmountIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldSettledAmount))
}

// SettledAmountNotNil applies the NotNil predicate on the "settled_amount" field.
func SettledAmountNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldSettledAmount))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpstreamBoundAtEQ applies the EQ predicate on the "upstream_bound_at" field.
func UpstreamBoundAtEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldUpstreamBoundAt, v))
}

// UpstreamBoundAtNEQ applies the NEQ predicate on the "upstream_bound_at" field.
func UpstreamBoundAtNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldUpstreamBoundAt, v))
}

// UpstreamBoundAtIn applies the In predicate on the "upstream_bound_at" field.
func UpstreamBoundAtIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldUpstreamBoundAt, vs...))
}

// UpstreamBoundAtNotIn applies the NotIn predicate on the "upstream_bound_at" field.
func UpstreamBoundAtNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldUpstreamBoundAt, vs...))
}

// UpstreamBoundAtGT applies the GT predicate on the "upstream_bound_at" field.
func UpstreamBoundAtGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldUpstreamBoundAt, v))
}

// UpstreamBoundAtGTE applies the GTE predicate on the "upstream_bound_at" field.
func UpstreamBoundAtGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldUpstreamBoundAt, v))
}

// UpstreamBoundAtLT applies the LT predicate on the "upstream_bound_at" field.
func UpstreamBoundAtLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldUpstreamBoundAt, v))
}

// UpstreamBoundAtLTE applies the LTE predicate on the "upstream_bound_at" field.
func UpstreamBoundAtLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldUpstreamBoundAt, v))
}

// UpstreamBoundAtIsNil applies the IsNil predicate on the "upstream_bound_at" field.
func UpstreamBoundAtIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldUpstreamBoundAt))
}

// UpstreamBoundAtNotNil applies the NotNil predicate on the "upstream_bound_at" field.
func UpstreamBoundAtNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldUpstreamBoundAt))
}

// ResultUpdatedAtEQ applies the EQ predicate on the "result_updated_at" field.
func ResultUpdatedAtEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldResultUpdatedAt, v))
}

// ResultUpdatedAtNEQ applies the NEQ predicate on the "result_updated_at" field.
func ResultUpdatedAtNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldResultUpdatedAt, v))
}

// ResultUpdatedAtIn applies the In predicate on the "result_updated_at" field.
func ResultUpdatedAtIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldResultUpdatedAt, vs...))
}

// ResultUpdatedAtNotIn applies the NotIn predicate on the "result_updated_at" field.
func ResultUpdatedAtNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldResultUpdatedAt, vs...))
}

// ResultUpdatedAtGT applies the GT predicate on the "result_updated_at" field.
func ResultUpdatedAtGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldResultUpdatedAt, v))
}

// ResultUpdatedAtGTE applies the GTE predicate on the "result_updated_at" field.
func ResultUpdatedAtGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldResultUpdatedAt, v))
}

// ResultUpdatedAtLT applies the LT predicate on the "result_updated_at" field.
func ResultUpdatedAtLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldResultUpdatedAt, v))
}

// ResultUpdatedAtLTE applies the LTE predicate on the "result_updated_at" field.
func ResultUpdatedAtLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldResultUpdatedAt, v))
}

// ResultUpdatedAtIsNil applies the IsNil predicate on the "result_updated_at" field.
func ResultUpdatedAtIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldResultUpdatedAt))
}

// ResultUpdatedAtNotNil applies the NotNil predicate on the "result_updated_at" field.
func ResultUpdatedAtNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldResultUpdatedAt))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldSettledAt, v))
}

// SettledAtIsNil applies the IsNil predicate on the "settled_at" field.
func SettledAtIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldSettledAt))
}

// SettledAtNotNil applies the NotNil predicate on the "settled_at" field.
func SettledAtNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldSettledAt))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.FieldNotNull(FieldClosedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GrsaiSettlement) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GrsaiSettlement) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GrsaiSettlement) predicate.GrsaiSettlement {
	return predicate.GrsaiSettlement(sql.NotPredicates(p))
}
