import { defineConfig } from 'vitepress'

export default defineConfig({
  lang: 'zh-CN',
  title: 'Gkotta 文档',
  description: 'Gkotta API 接入指南、客户端配置、计费与常见问题。',
  base: '/docs/',
  cleanUrls: true,
  outDir: '../../backend/internal/web/dist/docs',
  srcExclude: ['README.md'],
  lastUpdated: false,
  head: [['link', { rel: 'icon', href: '/docs/logo.svg' }]],
  themeConfig: {
    logo: '/logo.svg',
    siteTitle: 'Gkotta 文档',
    nav: [
      { text: '文档', link: '/' },
      { text: '主站', link: 'https://www.gkotta.bid', target: '_self' },
      { text: '控制台', link: 'https://www.gkotta.bid/login', target: '_self' },
    ],
    sidebar: [
      { text: '文档首页', link: '/' },
      { text: '开始使用', items: [
        { text: '简易使用', link: '/easy-use' },
        { text: '快速开始', link: '/quick-start' },
        { text: 'API 密钥与分组', link: '/api-keys' },
      ] },
      { text: '编程与 Agent', items: [
        { text: '客户端接入总览', link: '/clients' },
        { text: 'CC Switch', link: '/cc-switch' },
        { text: 'Claude Code', link: '/claude-code' },
        { text: 'Claude Desktop', link: '/claude-desktop' },
        { text: 'Codex', link: '/codex' },
        { text: 'Codex++', link: '/codex-plus' },
        { text: 'Hermes', link: '/hermes' },
        { text: 'OpenClaw', link: '/openclaw' },
        { text: 'OpenCode', link: '/opencode' },
        { text: 'Gemini CLI', link: '/gemini-cli' },
      ] },
      { text: 'API 参考', items: [
        { text: 'API 手册', link: '/api-manual' },
        { text: 'OpenAI 兼容 API', link: '/openai-api' },
        { text: 'Anthropic API', link: '/anthropic-api' },
        { text: 'Gemini API', link: '/gemini-api' },
        { text: '国内模型接入', link: '/domestic-models' },
      ] },
      { text: '图片与视频', items: [
        { text: '图像生成 API', link: '/image-generate' },
        { text: 'Grok 视频生成', link: '/video-generation' },
        { text: 'Seedance API', link: '/seedance-api' },
        { text: '图片转视频', link: '/image-to-video' },
      ] },
      { text: '使用场景', collapsed: false, items: [
        { text: '使用场景总览', link: '/scenarios/' },
        { text: '聊天与翻译', collapsed: true, items: [
          { text: 'Cherry Studio', link: '/scenarios/cherry-studio' },
          { text: 'Chatbox', link: '/scenarios/chatbox' },
          { text: 'NextChat', link: '/scenarios/nextchat' },
          { text: 'Open WebUI', link: '/scenarios/open-webui' },
          { text: '沉浸式翻译', link: '/scenarios/immersive-translate' },
          { text: 'Bob 翻译', link: '/scenarios/bob' },
        ] },
        { text: '编辑器', collapsed: true, items: [
          { text: 'Cursor', link: '/scenarios/cursor' },
          { text: 'Cline', link: '/scenarios/cline' },
          { text: 'Roo Code', link: '/scenarios/roo-code' },
          { text: 'Trae', link: '/scenarios/trae' },
        ] },
        { text: '工作流与开发', collapsed: true, items: [
          { text: 'Dify', link: '/scenarios/dify' },
          { text: 'LangChain', link: '/scenarios/langchain' },
          { text: 'FastClaw', link: '/scenarios/fastclaw' },
          { text: 'Paper2Any', link: '/scenarios/paper2any' },
          { text: 'Make Gemini 图像理解', link: '/scenarios/make-gemini-vision' },
          { text: '飞书多维表格生图', link: '/scenarios/lark-images' },
        ] },
      ] },
      { text: '账户与支持', items: [
        { text: '计费与用量', link: '/billing' },
        { text: '常见问题与排错', link: '/troubleshooting' },
      ] },
    ],
    outline: { level: [2, 3], label: '在此页面' },
    docFooter: { prev: '上一篇', next: '下一篇' },
    sidebarMenuLabel: '文档目录',
    returnToTopLabel: '返回顶部',
    darkModeSwitchLabel: '主题',
    lightModeSwitchTitle: '切换到浅色模式',
    darkModeSwitchTitle: '切换到深色模式',
    notFound: {
      title: '未找到这篇文档',
      quote: '链接可能已变更，请从目录或搜索中查找需要的内容。',
      linkLabel: '返回文档首页',
      linkText: '返回文档首页',
    },
    search: {
      provider: 'local',
      options: {
        translations: {
          button: { buttonText: '搜索文档', buttonAriaLabel: '搜索文档' },
          modal: {
            displayDetails: '显示详细信息',
            resetButtonTitle: '清除搜索',
            backButtonTitle: '返回',
            noResultsText: '没有找到相关结果',
            footer: { selectText: '选择', navigateText: '切换', closeText: '关闭' },
          },
        },
      },
    },
    footer: { message: '模型、价格与可用性以控制台实时信息为准。', copyright: 'Gkotta 使用文档' },
  },
})
